//
// DefaultAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class DefaultAPI {

    /**
     Health Check
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func healthCheckHealthGet() async throws -> AnyCodable {
        return try await healthCheckHealthGetWithRequestBuilder().execute().body
    }

    /**
     Health Check
     - GET /health
     - Health check endpoint. Returns app version + status — the `version` field is consumed by `tests/test_health.py` and surfaced in the `ops/server-monitor.sh` snapshot for cross- referencing post-deploy. Source: `app.config.settings.APP_VERSION` if defined, falling back to '0.0.0' for local runs.
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func healthCheckHealthGetWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/health"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Root
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func rootGet() async throws -> AnyCodable {
        return try await rootGetWithRequestBuilder().execute().body
    }

    /**
     Root
     - GET /
     - Root endpoint.
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func rootGetWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Serve Wechat Verification
     
     - parameter filename: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func serveWechatVerificationFilenameGet(filename: String) async throws -> AnyCodable {
        return try await serveWechatVerificationFilenameGetWithRequestBuilder(filename: filename).execute().body
    }

    /**
     Serve Wechat Verification
     - GET /{filename}
     - Serve WeChat domain verification files from static directory.
     - parameter filename: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func serveWechatVerificationFilenameGetWithRequestBuilder(filename: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/{filename}"
        let filenamePreEscape = "\(APIHelper.mapValueToPathItem(filename))"
        let filenamePostEscape = filenamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{filename}", with: filenamePostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
