//
// RoutesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class RoutesAPI {

    /**
     Charging Plan
     
     - parameter chargingPlanRequest: (body)  
     - returns: ChargingPlanResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func chargingPlanApiV1RoutesChargingPlanPost(chargingPlanRequest: ChargingPlanRequest) async throws -> ChargingPlanResponse {
        return try await chargingPlanApiV1RoutesChargingPlanPostWithRequestBuilder(chargingPlanRequest: chargingPlanRequest).execute().body
    }

    /**
     Charging Plan
     - POST /api/v1/routes/charging-plan
     - Phase 8.2: greedy charging-stop selection over client-provided candidate POIs. Pure computation — no map API call.
     - parameter chargingPlanRequest: (body)  
     - returns: RequestBuilder<ChargingPlanResponse> 
     */
    open class func chargingPlanApiV1RoutesChargingPlanPostWithRequestBuilder(chargingPlanRequest: ChargingPlanRequest) -> RequestBuilder<ChargingPlanResponse> {
        let localVariablePath = "/api/v1/routes/charging-plan"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: chargingPlanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChargingPlanResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Geocode Address
     
     - parameter geocodeRequest: (body)  
     - returns: GeocodeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func geocodeAddressApiV1RoutesGeocodePost(geocodeRequest: GeocodeRequest) async throws -> GeocodeResponse {
        return try await geocodeAddressApiV1RoutesGeocodePostWithRequestBuilder(geocodeRequest: geocodeRequest).execute().body
    }

    /**
     Geocode Address
     - POST /api/v1/routes/geocode
     - Convert address to coordinates.  Useful for getting coordinates from user-entered addresses.
     - parameter geocodeRequest: (body)  
     - returns: RequestBuilder<GeocodeResponse> 
     */
    open class func geocodeAddressApiV1RoutesGeocodePostWithRequestBuilder(geocodeRequest: GeocodeRequest) -> RequestBuilder<GeocodeResponse> {
        let localVariablePath = "/api/v1/routes/geocode"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: geocodeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GeocodeResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Get Route
     
     - parameter routeId: (path)  
     - returns: RoutePlanResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getRouteApiV1RoutesSavedRouteIdGet(routeId: Int) async throws -> RoutePlanResponse {
        return try await getRouteApiV1RoutesSavedRouteIdGetWithRequestBuilder(routeId: routeId).execute().body
    }

    /**
     Get Route
     - GET /api/v1/routes/saved/{route_id}
     - Get a saved route plan.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter routeId: (path)  
     - returns: RequestBuilder<RoutePlanResponse> 
     */
    open class func getRouteApiV1RoutesSavedRouteIdGetWithRequestBuilder(routeId: Int) -> RequestBuilder<RoutePlanResponse> {
        var localVariablePath = "/api/v1/routes/saved/{route_id}"
        let routeIdPreEscape = "\(APIHelper.mapValueToPathItem(routeId))"
        let routeIdPostEscape = routeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{route_id}", with: routeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoutePlanResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Routes
     
     - parameter limit: (query)  (optional, default to 10)
     - parameter offset: (query)  (optional, default to 0)
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listRoutesApiV1RoutesGet(limit: Int? = nil, offset: Int? = nil) async throws -> AnyCodable {
        return try await listRoutesApiV1RoutesGetWithRequestBuilder(limit: limit, offset: offset).execute().body
    }

    /**
     List Routes
     - GET /api/v1/routes/
     - List user's saved routes.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 10)
     - parameter offset: (query)  (optional, default to 0)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func listRoutesApiV1RoutesGetWithRequestBuilder(limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/routes/"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
            "offset": (wrappedValue: offset?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Navigate Route
     
     - parameter navigateRouteRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func navigateRouteApiV1RoutesNavigatePost(navigateRouteRequest: NavigateRouteRequest) async throws -> AnyCodable {
        return try await navigateRouteApiV1RoutesNavigatePostWithRequestBuilder(navigateRouteRequest: navigateRouteRequest).execute().body
    }

    /**
     Navigate Route
     - POST /api/v1/routes/navigate
     - Send planned route to vehicle.  Sends navigation waypoints to the vehicle's navigation system. By default, sends the charging stops as waypoints.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter navigateRouteRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func navigateRouteApiV1RoutesNavigatePostWithRequestBuilder(navigateRouteRequest: NavigateRouteRequest) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/routes/navigate"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: navigateRouteRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Navigate Saved Route
     
     - parameter routeId: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func navigateSavedRouteApiV1RoutesNavigateRouteIdPost(routeId: Int) async throws -> AnyCodable {
        return try await navigateSavedRouteApiV1RoutesNavigateRouteIdPostWithRequestBuilder(routeId: routeId).execute().body
    }

    /**
     Navigate Saved Route
     - POST /api/v1/routes/navigate/{route_id}
     - Send a saved route's charging stops + destination to the user's primary Tesla vehicle. Logic lives in `services/route_dispatch_service.send_saved_route_to_vehicle`.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter routeId: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func navigateSavedRouteApiV1RoutesNavigateRouteIdPostWithRequestBuilder(routeId: Int) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/routes/navigate/{route_id}"
        let routeIdPreEscape = "\(APIHelper.mapValueToPathItem(routeId))"
        let routeIdPostEscape = routeIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{route_id}", with: routeIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Reverse Geocode
     
     - parameter latitude: (query)  
     - parameter longitude: (query)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func reverseGeocodeApiV1RoutesReverseGeocodePost(latitude: Double, longitude: Double) async throws -> AnyCodable {
        return try await reverseGeocodeApiV1RoutesReverseGeocodePostWithRequestBuilder(latitude: latitude, longitude: longitude).execute().body
    }

    /**
     Reverse Geocode
     - POST /api/v1/routes/reverse-geocode
     - Convert coordinates to address.  Useful for displaying readable location names.
     - parameter latitude: (query)  
     - parameter longitude: (query)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func reverseGeocodeApiV1RoutesReverseGeocodePostWithRequestBuilder(latitude: Double, longitude: Double) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/routes/reverse-geocode"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "latitude": (wrappedValue: latitude.encodeToJSON(), isExplode: true),
            "longitude": (wrappedValue: longitude.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Route Only
     
     - parameter routeOnlyRequest: (body)  
     - returns: RouteOnlyResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func routeOnlyApiV1RoutesRoutePost(routeOnlyRequest: RouteOnlyRequest) async throws -> RouteOnlyResponse {
        return try await routeOnlyApiV1RoutesRoutePostWithRequestBuilder(routeOnlyRequest: routeOnlyRequest).execute().body
    }

    /**
     Route Only
     - POST /api/v1/routes/route
     - Phase 8.2: AMap routing only — polyline + distance + duration.  No POI search, no charging plan. iOS calls this first, then runs AMap SDK along-route POI search locally, then POSTs candidate POIs back to /routes/charging-plan to compute the greedy stops.
     - parameter routeOnlyRequest: (body)  
     - returns: RequestBuilder<RouteOnlyResponse> 
     */
    open class func routeOnlyApiV1RoutesRoutePostWithRequestBuilder(routeOnlyRequest: RouteOnlyRequest) -> RequestBuilder<RouteOnlyResponse> {
        let localVariablePath = "/api/v1/routes/route"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: routeOnlyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RouteOnlyResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Search Places
     
     - parameter keyword: (query)  
     - parameter location: (query)  (optional)
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func searchPlacesApiV1RoutesSearchGet(keyword: String, location: String? = nil) async throws -> AnyCodable {
        return try await searchPlacesApiV1RoutesSearchGetWithRequestBuilder(keyword: keyword, location: location).execute().body
    }

    /**
     Search Places
     - GET /api/v1/routes/search
     - Search for places by keyword.  Args:     keyword: Search keyword (e.g., city name, POI name)     location: Optional center location \"lat,lng\" for distance calculation  Returns:     List of matching places with name, address, location and distance
     - parameter keyword: (query)  
     - parameter location: (query)  (optional)
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func searchPlacesApiV1RoutesSearchGetWithRequestBuilder(keyword: String, location: String? = nil) -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/routes/search"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "keyword": (wrappedValue: keyword.encodeToJSON(), isExplode: true),
            "location": (wrappedValue: location?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
