//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UserAPI {

    /**
     Clear Scheduled Departure
     
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func clearScheduledDepartureApiV1UserScheduledDepartureDelete() async throws -> AnyCodable {
        return try await clearScheduledDepartureApiV1UserScheduledDepartureDeleteWithRequestBuilder().execute().body
    }

    /**
     Clear Scheduled Departure
     - DELETE /api/v1/user/scheduled-departure
     - Idempotent — clearing a non-existent row is a 200, not 404.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func clearScheduledDepartureApiV1UserScheduledDepartureDeleteWithRequestBuilder() -> RequestBuilder<AnyCodable> {
        let localVariablePath = "/api/v1/user/scheduled-departure"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Scheduled Departure
     
     - returns: ScheduledDepartureResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getScheduledDepartureApiV1UserScheduledDepartureGet() async throws -> ScheduledDepartureResponse {
        return try await getScheduledDepartureApiV1UserScheduledDepartureGetWithRequestBuilder().execute().body
    }

    /**
     Get Scheduled Departure
     - GET /api/v1/user/scheduled-departure
     - Fetch the user's active scheduled departure. Returns ``null`` when none is set — iOS treats null as \"not scheduled\" and shows the empty card.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - returns: RequestBuilder<ScheduledDepartureResponse> 
     */
    open class func getScheduledDepartureApiV1UserScheduledDepartureGetWithRequestBuilder() -> RequestBuilder<ScheduledDepartureResponse> {
        let localVariablePath = "/api/v1/user/scheduled-departure"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduledDepartureResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get User Settings
     
     - returns: UserSettingsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUserSettingsApiV1UserSettingsGet() async throws -> UserSettingsResponse {
        return try await getUserSettingsApiV1UserSettingsGetWithRequestBuilder().execute().body
    }

    /**
     Get User Settings
     - GET /api/v1/user/settings
     - Return the user's full settings dict. Empty dict when never set. `updated_at` is the most recent row update — clients use it to short-circuit re-fetches.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - returns: RequestBuilder<UserSettingsResponse> 
     */
    open class func getUserSettingsApiV1UserSettingsGetWithRequestBuilder() -> RequestBuilder<UserSettingsResponse> {
        let localVariablePath = "/api/v1/user/settings"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSettingsResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upsert Scheduled Departure
     
     - parameter scheduledDepartureRequest: (body)  
     - returns: ScheduledDepartureResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func upsertScheduledDepartureApiV1UserScheduledDeparturePut(scheduledDepartureRequest: ScheduledDepartureRequest) async throws -> ScheduledDepartureResponse {
        return try await upsertScheduledDepartureApiV1UserScheduledDeparturePutWithRequestBuilder(scheduledDepartureRequest: scheduledDepartureRequest).execute().body
    }

    /**
     Upsert Scheduled Departure
     - PUT /api/v1/user/scheduled-departure
     - Replace the user's scheduled departure with the supplied row. UNIQUE(user_id) enforces single-row semantics; we update in place when a row already exists rather than relying on the DB unique error to bubble up.  Past departures are accepted — the iOS UI prevents them, but a server reject would race with clock skew and break preheat cancellation flows.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter scheduledDepartureRequest: (body)  
     - returns: RequestBuilder<ScheduledDepartureResponse> 
     */
    open class func upsertScheduledDepartureApiV1UserScheduledDeparturePutWithRequestBuilder(scheduledDepartureRequest: ScheduledDepartureRequest) -> RequestBuilder<ScheduledDepartureResponse> {
        let localVariablePath = "/api/v1/user/scheduled-departure"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: scheduledDepartureRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduledDepartureResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upsert User Settings
     
     - parameter userSettingsRequest: (body)  
     - returns: UserSettingsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func upsertUserSettingsApiV1UserSettingsPut(userSettingsRequest: UserSettingsRequest) async throws -> UserSettingsResponse {
        return try await upsertUserSettingsApiV1UserSettingsPutWithRequestBuilder(userSettingsRequest: userSettingsRequest).execute().body
    }

    /**
     Upsert User Settings
     - PUT /api/v1/user/settings
     - Merge ``body.settings`` into the user's settings dict (or replace entirely if ``replace_all=true``). Each value is JSON-encoded for storage. Keys longer than 80 chars or empty are rejected (matches column constraint).
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter userSettingsRequest: (body)  
     - returns: RequestBuilder<UserSettingsResponse> 
     */
    open class func upsertUserSettingsApiV1UserSettingsPutWithRequestBuilder(userSettingsRequest: UserSettingsRequest) -> RequestBuilder<UserSettingsResponse> {
        let localVariablePath = "/api/v1/user/settings"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: userSettingsRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserSettingsResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
