//
// VehiclesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class VehiclesAPI {

    /**
     Cancel Queued Command
     
     - parameter queuedId: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDelete(queuedId: Int) async throws -> AnyCodable {
        return try await cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDeleteWithRequestBuilder(queuedId: queuedId).execute().body
    }

    /**
     Cancel Queued Command
     - DELETE /api/v1/vehicles/commands/queued/{queued_id}
     - Cancel a still-queued command before it drains. 404 if the user doesn't own it; 409 if it's already been sent/dropped.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter queuedId: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDeleteWithRequestBuilder(queuedId: Int) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/commands/queued/{queued_id}"
        let queuedIdPreEscape = "\(APIHelper.mapValueToPathItem(queuedId))"
        let queuedIdPostEscape = queuedIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{queued_id}", with: queuedIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Vehicle
     
     - parameter vehicleId: (path)  
     - returns: VehicleResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVehicleApiV1VehiclesVehicleIdGet(vehicleId: String) async throws -> VehicleResponse {
        return try await getVehicleApiV1VehiclesVehicleIdGetWithRequestBuilder(vehicleId: vehicleId).execute().body
    }

    /**
     Get Vehicle
     - GET /api/v1/vehicles/{vehicle_id}
     - Get specific vehicle details.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - returns: RequestBuilder<VehicleResponse> 
     */
    open class func getVehicleApiV1VehiclesVehicleIdGetWithRequestBuilder(vehicleId: String) -> RequestBuilder<VehicleResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VehicleResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Get Vehicle State
     
     - parameter vehicleId: (path)  
     - returns: VehicleStateResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getVehicleStateApiV1VehiclesVehicleIdStateGet(vehicleId: String) async throws -> VehicleStateResponse {
        return try await getVehicleStateApiV1VehiclesVehicleIdStateGetWithRequestBuilder(vehicleId: vehicleId).execute().body
    }

    /**
     Get Vehicle State
     - GET /api/v1/vehicles/{vehicle_id}/state
     - Get vehicle state (battery, location, etc.).  Returns real-time vehicle data including: - Battery level and range - Current location (GPS) - Charging state - Climate status
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - returns: RequestBuilder<VehicleStateResponse> 
     */
    open class func getVehicleStateApiV1VehiclesVehicleIdStateGetWithRequestBuilder(vehicleId: String) -> RequestBuilder<VehicleStateResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/state"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VehicleStateResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Charging Sessions
     
     - parameter vehicleId: (path)  
     - parameter limit: (query)  (optional, default to 50)
     - returns: ChargingSessionListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listChargingSessionsApiV1VehiclesVehicleIdSessionsGet(vehicleId: String, limit: Int? = nil) async throws -> ChargingSessionListResponse {
        return try await listChargingSessionsApiV1VehiclesVehicleIdSessionsGetWithRequestBuilder(vehicleId: vehicleId, limit: limit).execute().body
    }

    /**
     List Charging Sessions
     - GET /api/v1/vehicles/{vehicle_id}/sessions
     - Most-recent-first session list. Default limit 50 covers ~6 weeks of typical daily-charging owners; clients pass `?limit=N` to dig further. Strict per-user filter so a vehicle_id collision (Tesla sometimes recycles ids across accounts) can't leak rows.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter limit: (query)  (optional, default to 50)
     - returns: RequestBuilder<ChargingSessionListResponse> 
     */
    open class func listChargingSessionsApiV1VehiclesVehicleIdSessionsGetWithRequestBuilder(vehicleId: String, limit: Int? = nil) -> RequestBuilder<ChargingSessionListResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/sessions"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChargingSessionListResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Pending Commands
     
     - parameter limit: (query)  (optional, default to 20)
     - returns: PendingCommandListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listPendingCommandsApiV1VehiclesCommandsPendingGet(limit: Int? = nil) async throws -> PendingCommandListResponse {
        return try await listPendingCommandsApiV1VehiclesCommandsPendingGetWithRequestBuilder(limit: limit).execute().body
    }

    /**
     List Pending Commands
     - GET /api/v1/vehicles/commands/pending
     - Phase 9 — what VCP commands sent in the last few minutes are still awaiting telemetry confirmation, plus the most recently resolved ones for the iOS UI to flip to \"已关闭\" / \"超时\".  The resolver runs server-side on every Telemetry frame, so a well-timed poll right after dispatch will see the row transition pending → confirmed within ~1-2 s of the actual state change.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 20)
     - returns: RequestBuilder<PendingCommandListResponse> 
     */
    open class func listPendingCommandsApiV1VehiclesCommandsPendingGetWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<PendingCommandListResponse> {
        let localVariablePath = "/api/v1/vehicles/commands/pending"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PendingCommandListResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Queued Commands
     
     - parameter limit: (query)  (optional, default to 20)
     - returns: QueuedCommandListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listQueuedCommandsApiV1VehiclesCommandsQueuedGet(limit: Int? = nil) async throws -> QueuedCommandListResponse {
        return try await listQueuedCommandsApiV1VehiclesCommandsQueuedGetWithRequestBuilder(limit: limit).execute().body
    }

    /**
     List Queued Commands
     - GET /api/v1/vehicles/commands/queued
     - Return commands waiting on the car's next CONNECTED telemetry event, plus recently-resolved ones for the iOS UI to flip badges.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter limit: (query)  (optional, default to 20)
     - returns: RequestBuilder<QueuedCommandListResponse> 
     */
    open class func listQueuedCommandsApiV1VehiclesCommandsQueuedGetWithRequestBuilder(limit: Int? = nil) -> RequestBuilder<QueuedCommandListResponse> {
        let localVariablePath = "/api/v1/vehicles/commands/queued"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QueuedCommandListResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     List Vehicles
     
     - returns: VehicleListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listVehiclesApiV1VehiclesGet() async throws -> VehicleListResponse {
        return try await listVehiclesApiV1VehiclesGetWithRequestBuilder().execute().body
    }

    /**
     List Vehicles
     - GET /api/v1/vehicles/
     - List user's Tesla vehicles, syncing the local Vehicle table. Logic in services/vehicle_sync_service.sync_vehicles.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - returns: RequestBuilder<VehicleListResponse> 
     */
    open class func listVehiclesApiV1VehiclesGetWithRequestBuilder() -> RequestBuilder<VehicleListResponse> {
        let localVariablePath = "/api/v1/vehicles/"
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VehicleListResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Navigate Vehicle Address
     
     - parameter vehicleId: (path)  
     - parameter navigationAddressRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPost(vehicleId: String, navigationAddressRequest: NavigationAddressRequest) async throws -> AnyCodable {
        return try await navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPostWithRequestBuilder(vehicleId: vehicleId, navigationAddressRequest: navigationAddressRequest).execute().body
    }

    /**
     Navigate Vehicle Address
     - POST /api/v1/vehicles/{vehicle_id}/navigate/address
     - Send navigation destination by address to vehicle.  Sends address string to the vehicle's navigation system. Vehicle must be online.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter navigationAddressRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPostWithRequestBuilder(vehicleId: String, navigationAddressRequest: NavigationAddressRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/navigate/address"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: navigationAddressRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Navigate Vehicle
     
     - parameter vehicleId: (path)  
     - parameter navigationRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func navigateVehicleApiV1VehiclesVehicleIdNavigatePost(vehicleId: String, navigationRequest: NavigationRequest) async throws -> AnyCodable {
        return try await navigateVehicleApiV1VehiclesVehicleIdNavigatePostWithRequestBuilder(vehicleId: vehicleId, navigationRequest: navigationRequest).execute().body
    }

    /**
     Navigate Vehicle
     - POST /api/v1/vehicles/{vehicle_id}/navigate
     - Send GPS coordinates to vehicle nav. Dispatches through capability registry. Uses numeric vehicle_id (not VIN) since navigation_gps_request is one of the few endpoints not on the VCP-signed path.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter navigationRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func navigateVehicleApiV1VehiclesVehicleIdNavigatePostWithRequestBuilder(vehicleId: String, navigationRequest: NavigationRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/navigate"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: navigationRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Preheat Vehicle
     
     - parameter vehicleId: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func preheatVehicleApiV1VehiclesVehicleIdPreheatPost(vehicleId: String) async throws -> AnyCodable {
        return try await preheatVehicleApiV1VehiclesVehicleIdPreheatPostWithRequestBuilder(vehicleId: vehicleId).execute().body
    }

    /**
     Preheat Vehicle
     - POST /api/v1/vehicles/{vehicle_id}/preheat
     - Start HVAC (auto_conditioning_start) so the cabin is at temperature on arrival. Used by 出发前预热. Dispatches through capability registry.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func preheatVehicleApiV1VehiclesVehicleIdPreheatPostWithRequestBuilder(vehicleId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/preheat"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set Charge Limit
     
     - parameter vehicleId: (path)  
     - parameter chargeLimitRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setChargeLimitApiV1VehiclesVehicleIdChargeLimitPost(vehicleId: String, chargeLimitRequest: ChargeLimitRequest) async throws -> AnyCodable {
        return try await setChargeLimitApiV1VehiclesVehicleIdChargeLimitPostWithRequestBuilder(vehicleId: vehicleId, chargeLimitRequest: chargeLimitRequest).execute().body
    }

    /**
     Set Charge Limit
     - POST /api/v1/vehicles/{vehicle_id}/charge-limit
     - Set the vehicle's charge limit SOC percent (50..100). Dispatches through capability registry.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter chargeLimitRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func setChargeLimitApiV1VehiclesVehicleIdChargeLimitPostWithRequestBuilder(vehicleId: String, chargeLimitRequest: ChargeLimitRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/charge-limit"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: chargeLimitRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set Climate Keeper Mode
     
     - parameter vehicleId: (path)  
     - parameter climateKeeperModeRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePost(vehicleId: String, climateKeeperModeRequest: ClimateKeeperModeRequest) async throws -> AnyCodable {
        return try await setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePostWithRequestBuilder(vehicleId: vehicleId, climateKeeperModeRequest: climateKeeperModeRequest).execute().body
    }

    /**
     Set Climate Keeper Mode
     - POST /api/v1/vehicles/{vehicle_id}/climate-keeper-mode
     - Set climate keeper mode. 0=off / 1=keep / 2=dog / 3=camp. Dispatches through capability registry.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter climateKeeperModeRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePostWithRequestBuilder(vehicleId: String, climateKeeperModeRequest: ClimateKeeperModeRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/climate-keeper-mode"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: climateKeeperModeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set Primary Vehicle
     
     - parameter vehicleId: (path)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPost(vehicleId: String) async throws -> AnyCodable {
        return try await setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPostWithRequestBuilder(vehicleId: vehicleId).execute().body
    }

    /**
     Set Primary Vehicle
     - POST /api/v1/vehicles/{vehicle_id}/set-primary
     - Set vehicle as primary for the user.  Only one vehicle can be primary at a time.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPostWithRequestBuilder(vehicleId: String) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/set-primary"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Set Sentry Mode
     
     - parameter vehicleId: (path)  
     - parameter sentryModeRequest: (body)  
     - returns: AnyCodable
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func setSentryModeApiV1VehiclesVehicleIdSentryModePost(vehicleId: String, sentryModeRequest: SentryModeRequest) async throws -> AnyCodable {
        return try await setSentryModeApiV1VehiclesVehicleIdSentryModePostWithRequestBuilder(vehicleId: vehicleId, sentryModeRequest: sentryModeRequest).execute().body
    }

    /**
     Set Sentry Mode
     - POST /api/v1/vehicles/{vehicle_id}/sentry-mode
     - Toggle sentry mode. Dispatches through capability registry.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter sentryModeRequest: (body)  
     - returns: RequestBuilder<AnyCodable> 
     */
    open class func setSentryModeApiV1VehiclesVehicleIdSentryModePostWithRequestBuilder(vehicleId: String, sentryModeRequest: SentryModeRequest) -> RequestBuilder<AnyCodable> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/sentry-mode"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sentryModeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AnyCodable>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Suggest Charge Limit Endpoint
     
     - parameter vehicleId: (path)  
     - parameter suggestChargeLimitRequest: (body)  
     - returns: SuggestChargeLimitResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPost(vehicleId: String, suggestChargeLimitRequest: SuggestChargeLimitRequest) async throws -> SuggestChargeLimitResponse {
        return try await suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPostWithRequestBuilder(vehicleId: vehicleId, suggestChargeLimitRequest: suggestChargeLimitRequest).execute().body
    }

    /**
     Suggest Charge Limit Endpoint
     - POST /api/v1/vehicles/{vehicle_id}/suggest-charge-limit
     - Server-side mirror of iOS ChargeLimitSuggester. Reads the user's currently-stored ScheduledDeparture (A.3) to find any upcoming trip; daily/trip preferences come from the request body (Phase D will read them from /user/settings instead).
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter suggestChargeLimitRequest: (body)  
     - returns: RequestBuilder<SuggestChargeLimitResponse> 
     */
    open class func suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPostWithRequestBuilder(vehicleId: String, suggestChargeLimitRequest: SuggestChargeLimitRequest) -> RequestBuilder<SuggestChargeLimitResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/suggest-charge-limit"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: suggestChargeLimitRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SuggestChargeLimitResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Upsert Charging Session
     
     - parameter vehicleId: (path)  
     - parameter chargingSessionRequest: (body)  
     - returns: ChargingSessionResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func upsertChargingSessionApiV1VehiclesVehicleIdSessionsPost(vehicleId: String, chargingSessionRequest: ChargingSessionRequest) async throws -> ChargingSessionResponse {
        return try await upsertChargingSessionApiV1VehiclesVehicleIdSessionsPostWithRequestBuilder(vehicleId: vehicleId, chargingSessionRequest: chargingSessionRequest).execute().body
    }

    /**
     Upsert Charging Session
     - POST /api/v1/vehicles/{vehicle_id}/sessions
     - Create or update a charging session.  iOS POSTs once on plug-in (ended_at NULL) and again on plug-out (ended_at set). Server upserts on ``client_session_id`` so retries are safe; if absent (legacy iOS builds), every POST creates a new row — acceptable trade-off but fix client-side first.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - parameter chargingSessionRequest: (body)  
     - returns: RequestBuilder<ChargingSessionResponse> 
     */
    open class func upsertChargingSessionApiV1VehiclesVehicleIdSessionsPostWithRequestBuilder(vehicleId: String, chargingSessionRequest: ChargingSessionRequest) -> RequestBuilder<ChargingSessionResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/sessions"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: chargingSessionRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ChargingSessionResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Wake Vehicle
     
     - parameter vehicleId: (path)  
     - returns: WakeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func wakeVehicleApiV1VehiclesVehicleIdWakePost(vehicleId: String) async throws -> WakeResponse {
        return try await wakeVehicleApiV1VehiclesVehicleIdWakePostWithRequestBuilder(vehicleId: vehicleId).execute().body
    }

    /**
     Wake Vehicle
     - POST /api/v1/vehicles/{vehicle_id}/wake
     - Wake up the vehicle.  Sends wake-up command and waits for vehicle to come online. May take 10-30 seconds.
     - Bearer Token:
       - type: http
       - name: HTTPBearer
     - parameter vehicleId: (path)  
     - returns: RequestBuilder<WakeResponse> 
     */
    open class func wakeVehicleApiV1VehiclesVehicleIdWakePostWithRequestBuilder(vehicleId: String) -> RequestBuilder<WakeResponse> {
        var localVariablePath = "/api/v1/vehicles/{vehicle_id}/wake"
        let vehicleIdPreEscape = "\(APIHelper.mapValueToPathItem(vehicleId))"
        let vehicleIdPostEscape = vehicleIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{vehicle_id}", with: vehicleIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = TePlannerAPIAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<WakeResponse>.Type = TePlannerAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
