// Generated by scripts/generate-tokens.py — do not edit by hand.
// Source: packages/design-tokens/tokens.json

package cloud.teplanner.android.core.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

object Tokens {
    val colorAlertFiringBg = Color(0xFFD32F2F)
    val colorAlertFiringFg = Color(0xFFFFFFFF)
    val colorAlertFiringRowWash = Color(0xFFFFE5E5)
    val colorAlertSnoozeFg = Color(0xFFFF9800)
    val colorTriggerAccentCron = Color(0xFF1976D2)
    val colorTriggerAccentGeofence = Color(0xFF388E3C)
    val colorTriggerAccentStateTransition = Color(0xFF3F51B5)
    val colorTriggerAccentStateDuration = Color(0xFFF57C00)
    val colorTriggerAccentDefault = Color(0xFF0066CC)
    val colorBadgePresetBg = Color(0xFF1976D2)
    val colorBadgePresetBgAlpha = 0.15.dp
    val colorBadgePresetFg = Color(0xFF1976D2)
    val colorBadgeCustomBg = Color(0xFF388E3C)
    val colorBadgeCustomBgAlpha = 0.15.dp
    val colorBadgeCustomFg = Color(0xFF388E3C)
    val colorWashWarning = Color(0xFFFFA726)
    val colorWashWarningAlpha = 0.12.dp
    val colorWashSnooze = Color(0xFFFF9800)
    val colorWashSnoozeAlpha = 0.1.dp
    val colorWashPermission = Color(0xFFFFA726)
    val colorWashPermissionAlpha = 0.1.dp
    val spacingXs = 4.dp
    val spacingSm = 8.dp
    val spacingMd = 12.dp
    val spacingLg = 16.dp
    val spacingXl = 24.dp
    val spacingXxl = 32.dp
    val radiusCard = 12.dp
    val radiusTile = 8.dp
    val radiusCapsule = 50.dp
}
