// Generated by scripts/generate-tokens.py — do not edit by hand.
// Source: packages/design-tokens/tokens.json

package cloud.teplanner.android.core.ui

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object Tokens {
    val colorAlertFiringBg = Color(0xFFD32F2F)
    val colorAlertFiringFg = Color(0xFFFFFFFF)
    val colorAlertFiringRowWash = Color(0xFFFFE5E5)
    val colorAlertSnoozeFg = Color(0xFFFF9800)
    val colorTriggerAccentCron = Color(0xFF1976D2)
    val colorTriggerAccentGeofence = Color(0xFF388E3C)
    val colorTriggerAccentStateTransition = Color(0xFF3F51B5)
    val colorTriggerAccentStateDuration = Color(0xFFF57C00)
    val colorTriggerAccentDefault = Color(0xFF0066CC)
    val colorBadgePresetBg = Color(0xFF1976D2)
    val colorBadgePresetBgAlpha = 0.15.dp
    val colorBadgePresetFg = Color(0xFF1976D2)
    val colorBadgeCustomBg = Color(0xFF388E3C)
    val colorBadgeCustomBgAlpha = 0.15.dp
    val colorBadgeCustomFg = Color(0xFF388E3C)
    val colorWashWarning = Color(0xFFFFA726)
    val colorWashWarningAlpha = 0.12.dp
    val colorWashSnooze = Color(0xFFFF9800)
    val colorWashSnoozeAlpha = 0.1.dp
    val colorWashPermission = Color(0xFFFFA726)
    val colorWashPermissionAlpha = 0.1.dp
    // colorStateWaking: iOS-only (Color(.systemOrange)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorStateReady: iOS-only (Color(.systemGreen)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorStateOffline: iOS-only (Color(.systemGray)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorStateError: iOS-only (Color(.systemRed)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorBatteryCritical: iOS-only (Color(.systemRed)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorBatteryLow: iOS-only (Color(.systemOrange)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorBatteryNormal: iOS-only (Color(.systemBlue)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // colorBatteryFull: iOS-only (Color(.systemGreen)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    val colorRingTrackAlpha = 0.08.dp
    val spacingXs = 4.dp
    val spacingSm = 8.dp
    val spacingSmPlus = 10.dp
    val spacingMd = 12.dp
    val spacingMdPlus = 14.dp
    val spacingLg = 16.dp
    val spacingXl = 24.dp
    val spacingXxl = 32.dp
    val radiusCard = 12.dp
    val radiusTile = 8.dp
    val radiusCapsule = 50.dp
    val radiusHubCard = 14.dp
    // shadowSubtle: shadow spec (color=#000000 opacity=0.08 radius=1 y=0). Phase F: map to Compose elevation dp or custom drawShadow modifier.
    // shadowDefault: shadow spec (color=#000000 opacity=0.16 radius=2 y=0). Phase F: map to Compose elevation dp or custom drawShadow modifier.
    // shadowDrawer: shadow spec (color=#000000 opacity=0.12 radius=8 y=-2). Phase F: map to Compose elevation dp or custom drawShadow modifier.
    // surfaceCanvas: iOS-only (Color(.systemBackground)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // surfaceCard: iOS-only (Color(.secondarySystemBackground)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // surfaceElevated: iOS-only (Color(.tertiarySystemBackground)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    // surfaceFill: iOS-only (Color(.tertiarySystemFill)). Phase F: map to MaterialTheme.colorScheme.* equivalent.
    val typographyMetricHero = TextStyle(fontSize = 44.sp, fontWeight = FontWeight.SemiBold, fontFeatureSettings = "\"tnum\"")
    val typographyMetricCompact = TextStyle(fontSize = 22.sp, fontWeight = FontWeight.Bold, fontFeatureSettings = "\"tnum\"")
    val typographyCodeDisplay = TextStyle(fontSize = 48.sp, fontWeight = FontWeight.Bold, fontFamily = FontFamily.Monospace)
    val typographyCodeInput = TextStyle(fontSize = 28.sp, fontWeight = FontWeight.SemiBold, fontFamily = FontFamily.Monospace)
    val typographyPlaceholderIconSm = TextStyle(fontSize = 36.sp)
    val typographyPlaceholderIconMd = TextStyle(fontSize = 40.sp)
    val typographyPlaceholderIconLg = TextStyle(fontSize = 64.sp)
    val typographySplashLogo = TextStyle(fontSize = 96.sp, fontWeight = FontWeight.Bold)
}
