/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.ChargingSessionListResponse
import cloud.teplanner.api.models.ChargingSessionResponse

class ChargingSessionListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargingSessionListResponse
        //val modelInstance = ChargingSessionListResponse()

        // to test the property `sessions`
        should("test sessions") {
            // uncomment below to test the property
            //modelInstance.sessions shouldBe ("TODO")
        }

    }
}
