/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.ChargingStopResponse

class ChargingStopResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargingStopResponse
        //val modelInstance = ChargingStopResponse()

        // to test the property `stationId`
        should("test stationId") {
            // uncomment below to test the property
            //modelInstance.stationId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `distanceFromStartKm`
        should("test distanceFromStartKm") {
            // uncomment below to test the property
            //modelInstance.distanceFromStartKm shouldBe ("TODO")
        }

        // to test the property `arrivalSoc`
        should("test arrivalSoc") {
            // uncomment below to test the property
            //modelInstance.arrivalSoc shouldBe ("TODO")
        }

        // to test the property `departureSoc`
        should("test departureSoc") {
            // uncomment below to test the property
            //modelInstance.departureSoc shouldBe ("TODO")
        }

        // to test the property `chargingDurationMinutes`
        should("test chargingDurationMinutes") {
            // uncomment below to test the property
            //modelInstance.chargingDurationMinutes shouldBe ("TODO")
        }

        // to test the property `address`
        should("test address") {
            // uncomment below to test the property
            //modelInstance.address shouldBe ("TODO")
        }

        // to test the property ``operator``
        should("test `operator`") {
            // uncomment below to test the property
            //modelInstance.`operator` shouldBe ("TODO")
        }

    }
}
