/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.ChargingPlanRequest
import cloud.teplanner.api.models.POIInput

class ChargingPlanRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargingPlanRequest
        //val modelInstance = ChargingPlanRequest()

        // to test the property `polyline` - [[lat, lng], …]
        should("test polyline") {
            // uncomment below to test the property
            //modelInstance.polyline shouldBe ("TODO")
        }

        // to test the property `totalDistanceKm`
        should("test totalDistanceKm") {
            // uncomment below to test the property
            //modelInstance.totalDistanceKm shouldBe ("TODO")
        }

        // to test the property `candidatePois`
        should("test candidatePois") {
            // uncomment below to test the property
            //modelInstance.candidatePois shouldBe ("TODO")
        }

        // to test the property `initialSoc`
        should("test initialSoc") {
            // uncomment below to test the property
            //modelInstance.initialSoc shouldBe ("TODO")
        }

        // to test the property `carType`
        should("test carType") {
            // uncomment below to test the property
            //modelInstance.carType shouldBe ("TODO")
        }

        // to test the property `minArrivalSoc`
        should("test minArrivalSoc") {
            // uncomment below to test the property
            //modelInstance.minArrivalSoc shouldBe ("TODO")
        }

        // to test the property `vehicleRangeKm`
        should("test vehicleRangeKm") {
            // uncomment below to test the property
            //modelInstance.vehicleRangeKm shouldBe ("TODO")
        }

    }
}
