/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.NavigateRouteRequest
import cloud.teplanner.api.models.LocationInput

class NavigateRouteRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NavigateRouteRequest
        //val modelInstance = NavigateRouteRequest()

        // to test the property `vehicleId`
        should("test vehicleId") {
            // uncomment below to test the property
            //modelInstance.vehicleId shouldBe ("TODO")
        }

        // to test the property `waypoints`
        should("test waypoints") {
            // uncomment below to test the property
            //modelInstance.waypoints shouldBe ("TODO")
        }

    }
}
