/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.RecentFireEntry

class RecentFireEntryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecentFireEntry
        //val modelInstance = RecentFireEntry()

        // to test the property `kind`
        should("test kind") {
            // uncomment below to test the property
            //modelInstance.kind shouldBe ("TODO")
        }

        // to test the property `pushedAt`
        should("test pushedAt") {
            // uncomment below to test the property
            //modelInstance.pushedAt shouldBe ("TODO")
        }

        // to test the property `clearedAt`
        should("test clearedAt") {
            // uncomment below to test the property
            //modelInstance.clearedAt shouldBe ("TODO")
        }

    }
}
