/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.RegisterDeviceRequest

class RegisterDeviceRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegisterDeviceRequest
        //val modelInstance = RegisterDeviceRequest()

        // to test the property `token` - Provider device token (APNs hex / JPush registration_id / Huawei push token)
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `bundleId`
        should("test bundleId") {
            // uncomment below to test the property
            //modelInstance.bundleId shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `providerToken`
        should("test providerToken") {
            // uncomment below to test the property
            //modelInstance.providerToken shouldBe ("TODO")
        }

    }
}
