/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.RoutePlanResponse
import cloud.teplanner.api.models.ChargingStopResponse

class RoutePlanResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RoutePlanResponse
        //val modelInstance = RoutePlanResponse()

        // to test the property `arrivalSoc`
        should("test arrivalSoc") {
            // uncomment below to test the property
            //modelInstance.arrivalSoc shouldBe ("TODO")
        }

        // to test the property `chargingDurationMinutes`
        should("test chargingDurationMinutes") {
            // uncomment below to test the property
            //modelInstance.chargingDurationMinutes shouldBe ("TODO")
        }

        // to test the property `chargingStops`
        should("test chargingStops") {
            // uncomment below to test the property
            //modelInstance.chargingStops shouldBe ("TODO")
        }

        // to test the property `destination`
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `drivingDurationMinutes`
        should("test drivingDurationMinutes") {
            // uncomment below to test the property
            //modelInstance.drivingDurationMinutes shouldBe ("TODO")
        }

        // to test the property `initialSoc`
        should("test initialSoc") {
            // uncomment below to test the property
            //modelInstance.initialSoc shouldBe ("TODO")
        }

        // to test the property `numChargingStops`
        should("test numChargingStops") {
            // uncomment below to test the property
            //modelInstance.numChargingStops shouldBe ("TODO")
        }

        // to test the property `origin`
        should("test origin") {
            // uncomment below to test the property
            //modelInstance.origin shouldBe ("TODO")
        }

        // to test the property `totalDistanceKm`
        should("test totalDistanceKm") {
            // uncomment below to test the property
            //modelInstance.totalDistanceKm shouldBe ("TODO")
        }

        // to test the property `totalDurationMinutes`
        should("test totalDurationMinutes") {
            // uncomment below to test the property
            //modelInstance.totalDurationMinutes shouldBe ("TODO")
        }

        // to test the property `polyline`
        should("test polyline") {
            // uncomment below to test the property
            //modelInstance.polyline shouldBe ("TODO")
        }

        // to test the property `routeId`
        should("test routeId") {
            // uncomment below to test the property
            //modelInstance.routeId shouldBe ("TODO")
        }

        // to test the property `warnings`
        should("test warnings") {
            // uncomment below to test the property
            //modelInstance.warnings shouldBe ("TODO")
        }

    }
}
