/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.RuleOrderRequest

class RuleOrderRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RuleOrderRequest
        //val modelInstance = RuleOrderRequest()

        // to test the property `ruleIds` - Ordered list of rule ids. Position in the list becomes display_order (0 = first). Rules NOT in the list keep their existing display_order; pass an empty list combined with `clear=true` to reset all overrides.
        should("test ruleIds") {
            // uncomment below to test the property
            //modelInstance.ruleIds shouldBe ("TODO")
        }

        // to test the property `clear`
        should("test clear") {
            // uncomment below to test the property
            //modelInstance.clear shouldBe ("TODO")
        }

    }
}
