/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.RuleResponse

class RuleResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RuleResponse
        //val modelInstance = RuleResponse()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `presetId`
        should("test presetId") {
            // uncomment below to test the property
            //modelInstance.presetId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `enabled`
        should("test enabled") {
            // uncomment below to test the property
            //modelInstance.enabled shouldBe ("TODO")
        }

        // to test the property `spec`
        should("test spec") {
            // uncomment below to test the property
            //modelInstance.spec shouldBe ("TODO")
        }

        // to test the property `version`
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `lastFiredAt`
        should("test lastFiredAt") {
            // uncomment below to test the property
            //modelInstance.lastFiredAt shouldBe ("TODO")
        }

        // to test the property `displayOrder`
        should("test displayOrder") {
            // uncomment below to test the property
            //modelInstance.displayOrder shouldBe ("TODO")
        }

        // to test the property `isFiring`
        should("test isFiring") {
            // uncomment below to test the property
            //modelInstance.isFiring shouldBe ("TODO")
        }

        // to test the property `firingSince`
        should("test firingSince") {
            // uncomment below to test the property
            //modelInstance.firingSince shouldBe ("TODO")
        }

    }
}
