/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.SnoozeRequest

class SnoozeRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SnoozeRequest
        //val modelInstance = SnoozeRequest()

        // to test the property `until`
        should("test until") {
            // uncomment below to test the property
            //modelInstance.until shouldBe ("TODO")
        }

        // to test the property `hours`
        should("test hours") {
            // uncomment below to test the property
            //modelInstance.hours shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

    }
}
