/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.SuggestChargeLimitRequest

class SuggestChargeLimitRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuggestChargeLimitRequest
        //val modelInstance = SuggestChargeLimitRequest()

        // to test the property `currentLimit`
        should("test currentLimit") {
            // uncomment below to test the property
            //modelInstance.currentLimit shouldBe ("TODO")
        }

        // to test the property `dailyLimitSoc`
        should("test dailyLimitSoc") {
            // uncomment below to test the property
            //modelInstance.dailyLimitSoc shouldBe ("TODO")
        }

        // to test the property `tripLimitSoc`
        should("test tripLimitSoc") {
            // uncomment below to test the property
            //modelInstance.tripLimitSoc shouldBe ("TODO")
        }

        // to test the property `tripWindowHours`
        should("test tripWindowHours") {
            // uncomment below to test the property
            //modelInstance.tripWindowHours shouldBe ("TODO")
        }

    }
}
