/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.SuggestChargeLimitResponse

class SuggestChargeLimitResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SuggestChargeLimitResponse
        //val modelInstance = SuggestChargeLimitResponse()

        // to test the property `recommendedPercent`
        should("test recommendedPercent") {
            // uncomment below to test the property
            //modelInstance.recommendedPercent shouldBe ("TODO")
        }

        // to test the property `currentPercent`
        should("test currentPercent") {
            // uncomment below to test the property
            //modelInstance.currentPercent shouldBe ("TODO")
        }

        // to test the property `reason`
        should("test reason") {
            // uncomment below to test the property
            //modelInstance.reason shouldBe ("TODO")
        }

        // to test the property `hoursAway`
        should("test hoursAway") {
            // uncomment below to test the property
            //modelInstance.hoursAway shouldBe ("TODO")
        }

        // to test the property `alreadyMatches`
        should("test alreadyMatches") {
            // uncomment below to test the property
            //modelInstance.alreadyMatches shouldBe ("TODO")
        }

    }
}
