/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.TelemetryStateResponse
import cloud.teplanner.api.models.TelemetryStateEntry

class TelemetryStateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TelemetryStateResponse
        //val modelInstance = TelemetryStateResponse()

        // to test the property `vehicleId`
        should("test vehicleId") {
            // uncomment below to test the property
            //modelInstance.vehicleId shouldBe ("TODO")
        }

        // to test the property `propertyEntries`
        should("test propertyEntries") {
            // uncomment below to test the property
            //modelInstance.propertyEntries shouldBe ("TODO")
        }

    }
}
