/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.UserSettingsRequest

class UserSettingsRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserSettingsRequest
        //val modelInstance = UserSettingsRequest()

        // to test the property `settings` - Full settings document. PUT replaces the keys present in this dict but leaves untouched keys alone — pass `replace_all=true` to wipe and re-seed.
        should("test settings") {
            // uncomment below to test the property
            //modelInstance.settings shouldBe ("TODO")
        }

        // to test the property `replaceAll`
        should("test replaceAll") {
            // uncomment below to test the property
            //modelInstance.replaceAll shouldBe ("TODO")
        }

    }
}
