/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.models.VehicleStateResponse

class VehicleStateResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VehicleStateResponse
        //val modelInstance = VehicleStateResponse()

        // to test the property `vehicleId`
        should("test vehicleId") {
            // uncomment below to test the property
            //modelInstance.vehicleId shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `state`
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `batteryLevel`
        should("test batteryLevel") {
            // uncomment below to test the property
            //modelInstance.batteryLevel shouldBe ("TODO")
        }

        // to test the property `batteryRangeKm`
        should("test batteryRangeKm") {
            // uncomment below to test the property
            //modelInstance.batteryRangeKm shouldBe ("TODO")
        }

        // to test the property `usableBatteryLevel`
        should("test usableBatteryLevel") {
            // uncomment below to test the property
            //modelInstance.usableBatteryLevel shouldBe ("TODO")
        }

        // to test the property `chargingState`
        should("test chargingState") {
            // uncomment below to test the property
            //modelInstance.chargingState shouldBe ("TODO")
        }

        // to test the property `latitude`
        should("test latitude") {
            // uncomment below to test the property
            //modelInstance.latitude shouldBe ("TODO")
        }

        // to test the property `longitude`
        should("test longitude") {
            // uncomment below to test the property
            //modelInstance.longitude shouldBe ("TODO")
        }

        // to test the property `heading`
        should("test heading") {
            // uncomment below to test the property
            //modelInstance.heading shouldBe ("TODO")
        }

        // to test the property `speed`
        should("test speed") {
            // uncomment below to test the property
            //modelInstance.speed shouldBe ("TODO")
        }

        // to test the property `odometerKm`
        should("test odometerKm") {
            // uncomment below to test the property
            //modelInstance.odometerKm shouldBe ("TODO")
        }

        // to test the property `insideTemp`
        should("test insideTemp") {
            // uncomment below to test the property
            //modelInstance.insideTemp shouldBe ("TODO")
        }

        // to test the property `outsideTemp`
        should("test outsideTemp") {
            // uncomment below to test the property
            //modelInstance.outsideTemp shouldBe ("TODO")
        }

        // to test the property `climateKeeperMode`
        should("test climateKeeperMode") {
            // uncomment below to test the property
            //modelInstance.climateKeeperMode shouldBe ("TODO")
        }

        // to test the property `isClimateOn`
        should("test isClimateOn") {
            // uncomment below to test the property
            //modelInstance.isClimateOn shouldBe ("TODO")
        }

        // to test the property `sentryModeOn`
        should("test sentryModeOn") {
            // uncomment below to test the property
            //modelInstance.sentryModeOn shouldBe ("TODO")
        }

        // to test the property `cabinOverheatProtectionOn`
        should("test cabinOverheatProtectionOn") {
            // uncomment below to test the property
            //modelInstance.cabinOverheatProtectionOn shouldBe ("TODO")
        }

        // to test the property `chargeLimitSoc`
        should("test chargeLimitSoc") {
            // uncomment below to test the property
            //modelInstance.chargeLimitSoc shouldBe ("TODO")
        }

    }
}
