/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type RecentFiresResponse,
    RecentFiresResponseFromJSON,
    RecentFiresResponseToJSON,
} from '../models/RecentFiresResponse';
import {
    type RuleCreateRequest,
    RuleCreateRequestFromJSON,
    RuleCreateRequestToJSON,
} from '../models/RuleCreateRequest';
import {
    type RuleListResponse,
    RuleListResponseFromJSON,
    RuleListResponseToJSON,
} from '../models/RuleListResponse';
import {
    type RuleOrderRequest,
    RuleOrderRequestFromJSON,
    RuleOrderRequestToJSON,
} from '../models/RuleOrderRequest';
import {
    type RuleResponse,
    RuleResponseFromJSON,
    RuleResponseToJSON,
} from '../models/RuleResponse';
import {
    type RuleUpdateRequest,
    RuleUpdateRequestFromJSON,
    RuleUpdateRequestToJSON,
} from '../models/RuleUpdateRequest';
import {
    type SnoozeListResponse,
    SnoozeListResponseFromJSON,
    SnoozeListResponseToJSON,
} from '../models/SnoozeListResponse';
import {
    type SnoozeRequest,
    SnoozeRequestFromJSON,
    SnoozeRequestToJSON,
} from '../models/SnoozeRequest';
import {
    type SnoozeResponse,
    SnoozeResponseFromJSON,
    SnoozeResponseToJSON,
} from '../models/SnoozeResponse';
import {
    type TelemetryStateResponse,
    TelemetryStateResponseFromJSON,
    TelemetryStateResponseToJSON,
} from '../models/TelemetryStateResponse';

export interface CreateRuleApiV1AutomationsPostRequest {
    ruleCreateRequest: RuleCreateRequest;
}

export interface DeleteRuleApiV1AutomationsRuleIdDeleteRequest {
    ruleId: string;
}

export interface ListRecentFiresApiV1AutomationsRecentFiresGetRequest {
    limit?: number;
}

export interface ReorderRulesApiV1AutomationsOrderPutRequest {
    ruleOrderRequest: RuleOrderRequest;
}

export interface SnoozeRuleApiV1AutomationsRuleIdSnoozePostRequest {
    ruleId: string;
    snoozeRequest: SnoozeRequest;
}

export interface UnsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequest {
    ruleId: string;
}

export interface UpdateRuleApiV1AutomationsRuleIdPutRequest {
    ruleId: string;
    ruleUpdateRequest: RuleUpdateRequest;
}

/**
 * 
 */
export class AutomationsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRuleApiV1AutomationsPost without sending the request
     */
    async createRuleApiV1AutomationsPostRequestOpts(requestParameters: CreateRuleApiV1AutomationsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'ruleCreateRequest',
                'Required parameter "ruleCreateRequest" was null or undefined when calling createRuleApiV1AutomationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RuleCreateRequestToJSON(requestParameters['ruleCreateRequest']),
        };
    }

    /**
     * Create Rule
     */
    async createRuleApiV1AutomationsPostRaw(requestParameters: CreateRuleApiV1AutomationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuleResponse>> {
        const requestOptions = await this.createRuleApiV1AutomationsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuleResponseFromJSON(jsonValue));
    }

    /**
     * Create Rule
     */
    async createRuleApiV1AutomationsPost(requestParameters: CreateRuleApiV1AutomationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuleResponse> {
        const response = await this.createRuleApiV1AutomationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteRuleApiV1AutomationsRuleIdDelete without sending the request
     */
    async deleteRuleApiV1AutomationsRuleIdDeleteRequestOpts(requestParameters: DeleteRuleApiV1AutomationsRuleIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling deleteRuleApiV1AutomationsRuleIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/{rule_id}`;
        urlPath = urlPath.replace('{rule_id}', encodeURIComponent(String(requestParameters['ruleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete Rule
     */
    async deleteRuleApiV1AutomationsRuleIdDeleteRaw(requestParameters: DeleteRuleApiV1AutomationsRuleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.deleteRuleApiV1AutomationsRuleIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Delete Rule
     */
    async deleteRuleApiV1AutomationsRuleIdDelete(requestParameters: DeleteRuleApiV1AutomationsRuleIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.deleteRuleApiV1AutomationsRuleIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTelemetryStateApiV1AutomationsStateGet without sending the request
     */
    async getTelemetryStateApiV1AutomationsStateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/state`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return the user\'s telemetry-recorded entity state — the ``tel:*`` rows the Fleet Telemetry consumer writes into automation_state.  iOS calls this on each polling tick, before evaluating rules, and seeds the local engine memory with the server\'s ``since`` timestamps. The interpreter then prefers the earlier of (locally observed, server telemetry) when computing duration. That\'s what closes the \"已开启 0 分钟\" gap: the iOS HubView pill now reports the same elapsed time the server reports in push notifications.
     * Get Telemetry State
     */
    async getTelemetryStateApiV1AutomationsStateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TelemetryStateResponse>> {
        const requestOptions = await this.getTelemetryStateApiV1AutomationsStateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TelemetryStateResponseFromJSON(jsonValue));
    }

    /**
     * Return the user\'s telemetry-recorded entity state — the ``tel:*`` rows the Fleet Telemetry consumer writes into automation_state.  iOS calls this on each polling tick, before evaluating rules, and seeds the local engine memory with the server\'s ``since`` timestamps. The interpreter then prefers the earlier of (locally observed, server telemetry) when computing duration. That\'s what closes the \"已开启 0 分钟\" gap: the iOS HubView pill now reports the same elapsed time the server reports in push notifications.
     * Get Telemetry State
     */
    async getTelemetryStateApiV1AutomationsStateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TelemetryStateResponse> {
        const response = await this.getTelemetryStateApiV1AutomationsStateGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listCapabilitiesApiV1AutomationsCapabilitiesGet without sending the request
     */
    async listCapabilitiesApiV1AutomationsCapabilitiesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/automations/capabilities`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Registry introspection. iOS visual builder calls this once at boot to populate the action-block picker.
     * List Capabilities
     */
    async listCapabilitiesApiV1AutomationsCapabilitiesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: Array<object>; }>> {
        const requestOptions = await this.listCapabilitiesApiV1AutomationsCapabilitiesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Registry introspection. iOS visual builder calls this once at boot to populate the action-block picker.
     * List Capabilities
     */
    async listCapabilitiesApiV1AutomationsCapabilitiesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: Array<object>; }> {
        const response = await this.listCapabilitiesApiV1AutomationsCapabilitiesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRecentFiresApiV1AutomationsRecentFiresGet without sending the request
     */
    async listRecentFiresApiV1AutomationsRecentFiresGetRequestOpts(requestParameters: ListRecentFiresApiV1AutomationsRecentFiresGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/recent-fires`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Recent rule-fire timeline for the user. Drives the iOS \'活动\' page — answers \'did my露营 rule fire today?\' without the user having to scrub through notification center.
     * List Recent Fires
     */
    async listRecentFiresApiV1AutomationsRecentFiresGetRaw(requestParameters: ListRecentFiresApiV1AutomationsRecentFiresGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecentFiresResponse>> {
        const requestOptions = await this.listRecentFiresApiV1AutomationsRecentFiresGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecentFiresResponseFromJSON(jsonValue));
    }

    /**
     * Recent rule-fire timeline for the user. Drives the iOS \'活动\' page — answers \'did my露营 rule fire today?\' without the user having to scrub through notification center.
     * List Recent Fires
     */
    async listRecentFiresApiV1AutomationsRecentFiresGet(requestParameters: ListRecentFiresApiV1AutomationsRecentFiresGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecentFiresResponse> {
        const response = await this.listRecentFiresApiV1AutomationsRecentFiresGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRulesApiV1AutomationsGet without sending the request
     */
    async listRulesApiV1AutomationsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all of the user\'s rules. Lazy-seeds the presets on first call (when user has zero rules). Order is canonical: each preset in its ALL_PRESETS-declared position, user-authored rules after, by creation time. Each rule includes ``last_fired_at`` — the most recent PushedAlert.pushed_at for that rule\'s kind.
     * List Rules
     */
    async listRulesApiV1AutomationsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuleListResponse>> {
        const requestOptions = await this.listRulesApiV1AutomationsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuleListResponseFromJSON(jsonValue));
    }

    /**
     * List all of the user\'s rules. Lazy-seeds the presets on first call (when user has zero rules). Order is canonical: each preset in its ALL_PRESETS-declared position, user-authored rules after, by creation time. Each rule includes ``last_fired_at`` — the most recent PushedAlert.pushed_at for that rule\'s kind.
     * List Rules
     */
    async listRulesApiV1AutomationsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuleListResponse> {
        const response = await this.listRulesApiV1AutomationsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSnoozesApiV1AutomationsSnoozesGet without sending the request
     */
    async listSnoozesApiV1AutomationsSnoozesGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/snoozes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all active (snoozed_until_utc > now) snoozes for the user. Stale rows (past their window) are filtered server-side; the client never sees them, so iOS doesn\'t need to time-check.
     * List Snoozes
     */
    async listSnoozesApiV1AutomationsSnoozesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnoozeListResponse>> {
        const requestOptions = await this.listSnoozesApiV1AutomationsSnoozesGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnoozeListResponseFromJSON(jsonValue));
    }

    /**
     * List all active (snoozed_until_utc > now) snoozes for the user. Stale rows (past their window) are filtered server-side; the client never sees them, so iOS doesn\'t need to time-check.
     * List Snoozes
     */
    async listSnoozesApiV1AutomationsSnoozesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnoozeListResponse> {
        const response = await this.listSnoozesApiV1AutomationsSnoozesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reorderRulesApiV1AutomationsOrderPut without sending the request
     */
    async reorderRulesApiV1AutomationsOrderPutRequestOpts(requestParameters: ReorderRulesApiV1AutomationsOrderPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'ruleOrderRequest',
                'Required parameter "ruleOrderRequest" was null or undefined when calling reorderRulesApiV1AutomationsOrderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/order`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RuleOrderRequestToJSON(requestParameters['ruleOrderRequest']),
        };
    }

    /**
     * Persist a user-defined display order. Returns the full rule list in the new canonical order so iOS can replace its in-memory cache in one round-trip.  All rule_ids must belong to the requesting user; we 404 on the first mismatch (defensive — silent skipping would leak existence). Duplicates within rule_ids are rejected (400) so position is well-defined.
     * Reorder Rules
     */
    async reorderRulesApiV1AutomationsOrderPutRaw(requestParameters: ReorderRulesApiV1AutomationsOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuleListResponse>> {
        const requestOptions = await this.reorderRulesApiV1AutomationsOrderPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuleListResponseFromJSON(jsonValue));
    }

    /**
     * Persist a user-defined display order. Returns the full rule list in the new canonical order so iOS can replace its in-memory cache in one round-trip.  All rule_ids must belong to the requesting user; we 404 on the first mismatch (defensive — silent skipping would leak existence). Duplicates within rule_ids are rejected (400) so position is well-defined.
     * Reorder Rules
     */
    async reorderRulesApiV1AutomationsOrderPut(requestParameters: ReorderRulesApiV1AutomationsOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuleListResponse> {
        const response = await this.reorderRulesApiV1AutomationsOrderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for snoozeRuleApiV1AutomationsRuleIdSnoozePost without sending the request
     */
    async snoozeRuleApiV1AutomationsRuleIdSnoozePostRequestOpts(requestParameters: SnoozeRuleApiV1AutomationsRuleIdSnoozePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling snoozeRuleApiV1AutomationsRuleIdSnoozePost().'
            );
        }

        if (requestParameters['snoozeRequest'] == null) {
            throw new runtime.RequiredError(
                'snoozeRequest',
                'Required parameter "snoozeRequest" was null or undefined when calling snoozeRuleApiV1AutomationsRuleIdSnoozePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/{rule_id}/snooze`;
        urlPath = urlPath.replace('{rule_id}', encodeURIComponent(String(requestParameters['ruleId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SnoozeRequestToJSON(requestParameters['snoozeRequest']),
        };
    }

    /**
     * Snooze ``rule_id`` until ``until`` (absolute UTC) or for ``hours`` from now. Exactly one of the two must be provided. Replaces any existing snooze on that rule (UNIQUE on rule_id).
     * Snooze Rule
     */
    async snoozeRuleApiV1AutomationsRuleIdSnoozePostRaw(requestParameters: SnoozeRuleApiV1AutomationsRuleIdSnoozePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SnoozeResponse>> {
        const requestOptions = await this.snoozeRuleApiV1AutomationsRuleIdSnoozePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SnoozeResponseFromJSON(jsonValue));
    }

    /**
     * Snooze ``rule_id`` until ``until`` (absolute UTC) or for ``hours`` from now. Exactly one of the two must be provided. Replaces any existing snooze on that rule (UNIQUE on rule_id).
     * Snooze Rule
     */
    async snoozeRuleApiV1AutomationsRuleIdSnoozePost(requestParameters: SnoozeRuleApiV1AutomationsRuleIdSnoozePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SnoozeResponse> {
        const response = await this.snoozeRuleApiV1AutomationsRuleIdSnoozePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for unsnoozeRuleApiV1AutomationsRuleIdSnoozeDelete without sending the request
     */
    async unsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequestOpts(requestParameters: UnsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling unsnoozeRuleApiV1AutomationsRuleIdSnoozeDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/{rule_id}/snooze`;
        urlPath = urlPath.replace('{rule_id}', encodeURIComponent(String(requestParameters['ruleId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Clear any active snooze on ``rule_id``. 404 if the rule itself doesn\'t exist; idempotent on a rule with no active snooze.
     * Unsnooze Rule
     */
    async unsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRaw(requestParameters: UnsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.unsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Clear any active snooze on ``rule_id``. 404 if the rule itself doesn\'t exist; idempotent on a rule with no active snooze.
     * Unsnooze Rule
     */
    async unsnoozeRuleApiV1AutomationsRuleIdSnoozeDelete(requestParameters: UnsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.unsnoozeRuleApiV1AutomationsRuleIdSnoozeDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateRuleApiV1AutomationsRuleIdPut without sending the request
     */
    async updateRuleApiV1AutomationsRuleIdPutRequestOpts(requestParameters: UpdateRuleApiV1AutomationsRuleIdPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ruleId'] == null) {
            throw new runtime.RequiredError(
                'ruleId',
                'Required parameter "ruleId" was null or undefined when calling updateRuleApiV1AutomationsRuleIdPut().'
            );
        }

        if (requestParameters['ruleUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'ruleUpdateRequest',
                'Required parameter "ruleUpdateRequest" was null or undefined when calling updateRuleApiV1AutomationsRuleIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/automations/{rule_id}`;
        urlPath = urlPath.replace('{rule_id}', encodeURIComponent(String(requestParameters['ruleId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: RuleUpdateRequestToJSON(requestParameters['ruleUpdateRequest']),
        };
    }

    /**
     * Update Rule
     */
    async updateRuleApiV1AutomationsRuleIdPutRaw(requestParameters: UpdateRuleApiV1AutomationsRuleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RuleResponse>> {
        const requestOptions = await this.updateRuleApiV1AutomationsRuleIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RuleResponseFromJSON(jsonValue));
    }

    /**
     * Update Rule
     */
    async updateRuleApiV1AutomationsRuleIdPut(requestParameters: UpdateRuleApiV1AutomationsRuleIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RuleResponse> {
        const response = await this.updateRuleApiV1AutomationsRuleIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
