/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type RegisterDeviceRequest,
    RegisterDeviceRequestFromJSON,
    RegisterDeviceRequestToJSON,
} from '../models/RegisterDeviceRequest';
import {
    type RegisterDeviceResponse,
    RegisterDeviceResponseFromJSON,
    RegisterDeviceResponseToJSON,
} from '../models/RegisterDeviceResponse';
import {
    type TestPushRequest,
    TestPushRequestFromJSON,
    TestPushRequestToJSON,
} from '../models/TestPushRequest';

export interface RegisterDeviceApiV1DevicesRegisterPostRequest {
    registerDeviceRequest: RegisterDeviceRequest;
}

export interface TestPushApiV1DevicesTestPushPostRequest {
    testPushRequest: TestPushRequest;
}

/**
 * 
 */
export class DevicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for registerDeviceApiV1DevicesRegisterPost without sending the request
     */
    async registerDeviceApiV1DevicesRegisterPostRequestOpts(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerDeviceRequest'] == null) {
            throw new runtime.RequiredError(
                'registerDeviceRequest',
                'Required parameter "registerDeviceRequest" was null or undefined when calling registerDeviceApiV1DevicesRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDeviceRequestToJSON(requestParameters['registerDeviceRequest']),
        };
    }

    /**
     * Upsert (user_id, token). Re-registering an existing token just bumps last_seen_at — that lets the polling layer prune stale rows later (e.g. tokens not seen for 30 days are likely uninstalled).
     * Register Device
     */
    async registerDeviceApiV1DevicesRegisterPostRaw(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterDeviceResponse>> {
        const requestOptions = await this.registerDeviceApiV1DevicesRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterDeviceResponseFromJSON(jsonValue));
    }

    /**
     * Upsert (user_id, token). Re-registering an existing token just bumps last_seen_at — that lets the polling layer prune stale rows later (e.g. tokens not seen for 30 days are likely uninstalled).
     * Register Device
     */
    async registerDeviceApiV1DevicesRegisterPost(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterDeviceResponse> {
        const response = await this.registerDeviceApiV1DevicesRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for runAutomationTickApiV1DevicesRunAutomationTickPost without sending the request
     */
    async runAutomationTickApiV1DevicesRunAutomationTickPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/run-automation-tick`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Trigger a single polling tick on demand. Used for end-to-end debugging: hit this, watch server.log, verify a push lands. Doesn\'t take args — runs the full eligible-user loop.
     * Run Automation Tick
     */
    async runAutomationTickApiV1DevicesRunAutomationTickPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.runAutomationTickApiV1DevicesRunAutomationTickPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Trigger a single polling tick on demand. Used for end-to-end debugging: hit this, watch server.log, verify a push lands. Doesn\'t take args — runs the full eligible-user loop.
     * Run Automation Tick
     */
    async runAutomationTickApiV1DevicesRunAutomationTickPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.runAutomationTickApiV1DevicesRunAutomationTickPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for testPushApiV1DevicesTestPushPost without sending the request
     */
    async testPushApiV1DevicesTestPushPostRequestOpts(requestParameters: TestPushApiV1DevicesTestPushPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['testPushRequest'] == null) {
            throw new runtime.RequiredError(
                'testPushRequest',
                'Required parameter "testPushRequest" was null or undefined when calling testPushApiV1DevicesTestPushPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/devices/test-push`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TestPushRequestToJSON(requestParameters['testPushRequest']),
        };
    }

    /**
     * Send a debug push to all of this user\'s registered devices. Phase E — routes through PushDispatcher so APNs / JPush / Huawei Push Kit all receive it according to each token\'s platform field.
     * Test Push
     */
    async testPushApiV1DevicesTestPushPostRaw(requestParameters: TestPushApiV1DevicesTestPushPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.testPushApiV1DevicesTestPushPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Send a debug push to all of this user\'s registered devices. Phase E — routes through PushDispatcher so APNs / JPush / Huawei Push Kit all receive it according to each token\'s platform field.
     * Test Push
     */
    async testPushApiV1DevicesTestPushPost(requestParameters: TestPushApiV1DevicesTestPushPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.testPushApiV1DevicesTestPushPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
