/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ChargingPlanRequest,
    ChargingPlanRequestFromJSON,
    ChargingPlanRequestToJSON,
} from '../models/ChargingPlanRequest';
import {
    type ChargingPlanResponse,
    ChargingPlanResponseFromJSON,
    ChargingPlanResponseToJSON,
} from '../models/ChargingPlanResponse';
import {
    type GeocodeRequest,
    GeocodeRequestFromJSON,
    GeocodeRequestToJSON,
} from '../models/GeocodeRequest';
import {
    type GeocodeResponse,
    GeocodeResponseFromJSON,
    GeocodeResponseToJSON,
} from '../models/GeocodeResponse';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';
import {
    type NavigateRouteRequest,
    NavigateRouteRequestFromJSON,
    NavigateRouteRequestToJSON,
} from '../models/NavigateRouteRequest';
import {
    type RouteOnlyRequest,
    RouteOnlyRequestFromJSON,
    RouteOnlyRequestToJSON,
} from '../models/RouteOnlyRequest';
import {
    type RouteOnlyResponse,
    RouteOnlyResponseFromJSON,
    RouteOnlyResponseToJSON,
} from '../models/RouteOnlyResponse';
import {
    type RoutePlanResponse,
    RoutePlanResponseFromJSON,
    RoutePlanResponseToJSON,
} from '../models/RoutePlanResponse';

export interface ChargingPlanApiV1RoutesChargingPlanPostRequest {
    chargingPlanRequest: ChargingPlanRequest;
}

export interface GeocodeAddressApiV1RoutesGeocodePostRequest {
    geocodeRequest: GeocodeRequest;
}

export interface GetRouteApiV1RoutesSavedRouteIdGetRequest {
    routeId: number;
}

export interface ListRoutesApiV1RoutesGetRequest {
    limit?: number;
    offset?: number;
}

export interface NavigateRouteApiV1RoutesNavigatePostRequest {
    navigateRouteRequest: NavigateRouteRequest;
}

export interface NavigateSavedRouteApiV1RoutesNavigateRouteIdPostRequest {
    routeId: number;
}

export interface ReverseGeocodeApiV1RoutesReverseGeocodePostRequest {
    latitude: number;
    longitude: number;
}

export interface RouteOnlyApiV1RoutesRoutePostRequest {
    routeOnlyRequest: RouteOnlyRequest;
}

export interface SearchPlacesApiV1RoutesSearchGetRequest {
    keyword: string;
    location?: string | null;
}

/**
 * 
 */
export class RoutesApi extends runtime.BaseAPI {

    /**
     * Creates request options for chargingPlanApiV1RoutesChargingPlanPost without sending the request
     */
    async chargingPlanApiV1RoutesChargingPlanPostRequestOpts(requestParameters: ChargingPlanApiV1RoutesChargingPlanPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chargingPlanRequest'] == null) {
            throw new runtime.RequiredError(
                'chargingPlanRequest',
                'Required parameter "chargingPlanRequest" was null or undefined when calling chargingPlanApiV1RoutesChargingPlanPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/routes/charging-plan`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChargingPlanRequestToJSON(requestParameters['chargingPlanRequest']),
        };
    }

    /**
     * Phase 8.2: greedy charging-stop selection over client-provided candidate POIs. Pure computation — no map API call.
     * Charging Plan
     */
    async chargingPlanApiV1RoutesChargingPlanPostRaw(requestParameters: ChargingPlanApiV1RoutesChargingPlanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChargingPlanResponse>> {
        const requestOptions = await this.chargingPlanApiV1RoutesChargingPlanPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChargingPlanResponseFromJSON(jsonValue));
    }

    /**
     * Phase 8.2: greedy charging-stop selection over client-provided candidate POIs. Pure computation — no map API call.
     * Charging Plan
     */
    async chargingPlanApiV1RoutesChargingPlanPost(requestParameters: ChargingPlanApiV1RoutesChargingPlanPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChargingPlanResponse> {
        const response = await this.chargingPlanApiV1RoutesChargingPlanPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for geocodeAddressApiV1RoutesGeocodePost without sending the request
     */
    async geocodeAddressApiV1RoutesGeocodePostRequestOpts(requestParameters: GeocodeAddressApiV1RoutesGeocodePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['geocodeRequest'] == null) {
            throw new runtime.RequiredError(
                'geocodeRequest',
                'Required parameter "geocodeRequest" was null or undefined when calling geocodeAddressApiV1RoutesGeocodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/routes/geocode`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeocodeRequestToJSON(requestParameters['geocodeRequest']),
        };
    }

    /**
     * Convert address to coordinates.  Useful for getting coordinates from user-entered addresses.
     * Geocode Address
     */
    async geocodeAddressApiV1RoutesGeocodePostRaw(requestParameters: GeocodeAddressApiV1RoutesGeocodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GeocodeResponse>> {
        const requestOptions = await this.geocodeAddressApiV1RoutesGeocodePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GeocodeResponseFromJSON(jsonValue));
    }

    /**
     * Convert address to coordinates.  Useful for getting coordinates from user-entered addresses.
     * Geocode Address
     */
    async geocodeAddressApiV1RoutesGeocodePost(requestParameters: GeocodeAddressApiV1RoutesGeocodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GeocodeResponse> {
        const response = await this.geocodeAddressApiV1RoutesGeocodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getRouteApiV1RoutesSavedRouteIdGet without sending the request
     */
    async getRouteApiV1RoutesSavedRouteIdGetRequestOpts(requestParameters: GetRouteApiV1RoutesSavedRouteIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling getRouteApiV1RoutesSavedRouteIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/routes/saved/{route_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a saved route plan.
     * Get Route
     */
    async getRouteApiV1RoutesSavedRouteIdGetRaw(requestParameters: GetRouteApiV1RoutesSavedRouteIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoutePlanResponse>> {
        const requestOptions = await this.getRouteApiV1RoutesSavedRouteIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoutePlanResponseFromJSON(jsonValue));
    }

    /**
     * Get a saved route plan.
     * Get Route
     */
    async getRouteApiV1RoutesSavedRouteIdGet(requestParameters: GetRouteApiV1RoutesSavedRouteIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoutePlanResponse> {
        const response = await this.getRouteApiV1RoutesSavedRouteIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listRoutesApiV1RoutesGet without sending the request
     */
    async listRoutesApiV1RoutesGetRequestOpts(requestParameters: ListRoutesApiV1RoutesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/routes/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List user\'s saved routes.
     * List Routes
     */
    async listRoutesApiV1RoutesGetRaw(requestParameters: ListRoutesApiV1RoutesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listRoutesApiV1RoutesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * List user\'s saved routes.
     * List Routes
     */
    async listRoutesApiV1RoutesGet(requestParameters: ListRoutesApiV1RoutesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listRoutesApiV1RoutesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for navigateRouteApiV1RoutesNavigatePost without sending the request
     */
    async navigateRouteApiV1RoutesNavigatePostRequestOpts(requestParameters: NavigateRouteApiV1RoutesNavigatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['navigateRouteRequest'] == null) {
            throw new runtime.RequiredError(
                'navigateRouteRequest',
                'Required parameter "navigateRouteRequest" was null or undefined when calling navigateRouteApiV1RoutesNavigatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/routes/navigate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NavigateRouteRequestToJSON(requestParameters['navigateRouteRequest']),
        };
    }

    /**
     * Send planned route to vehicle.  Sends navigation waypoints to the vehicle\'s navigation system. By default, sends the charging stops as waypoints.
     * Navigate Route
     */
    async navigateRouteApiV1RoutesNavigatePostRaw(requestParameters: NavigateRouteApiV1RoutesNavigatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.navigateRouteApiV1RoutesNavigatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Send planned route to vehicle.  Sends navigation waypoints to the vehicle\'s navigation system. By default, sends the charging stops as waypoints.
     * Navigate Route
     */
    async navigateRouteApiV1RoutesNavigatePost(requestParameters: NavigateRouteApiV1RoutesNavigatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.navigateRouteApiV1RoutesNavigatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for navigateSavedRouteApiV1RoutesNavigateRouteIdPost without sending the request
     */
    async navigateSavedRouteApiV1RoutesNavigateRouteIdPostRequestOpts(requestParameters: NavigateSavedRouteApiV1RoutesNavigateRouteIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeId'] == null) {
            throw new runtime.RequiredError(
                'routeId',
                'Required parameter "routeId" was null or undefined when calling navigateSavedRouteApiV1RoutesNavigateRouteIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/routes/navigate/{route_id}`;
        urlPath = urlPath.replace('{route_id}', encodeURIComponent(String(requestParameters['routeId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Send a saved route\'s charging stops + destination to the user\'s primary Tesla vehicle. Logic lives in `services/route_dispatch_service.send_saved_route_to_vehicle`.
     * Navigate Saved Route
     */
    async navigateSavedRouteApiV1RoutesNavigateRouteIdPostRaw(requestParameters: NavigateSavedRouteApiV1RoutesNavigateRouteIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.navigateSavedRouteApiV1RoutesNavigateRouteIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Send a saved route\'s charging stops + destination to the user\'s primary Tesla vehicle. Logic lives in `services/route_dispatch_service.send_saved_route_to_vehicle`.
     * Navigate Saved Route
     */
    async navigateSavedRouteApiV1RoutesNavigateRouteIdPost(requestParameters: NavigateSavedRouteApiV1RoutesNavigateRouteIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.navigateSavedRouteApiV1RoutesNavigateRouteIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for reverseGeocodeApiV1RoutesReverseGeocodePost without sending the request
     */
    async reverseGeocodeApiV1RoutesReverseGeocodePostRequestOpts(requestParameters: ReverseGeocodeApiV1RoutesReverseGeocodePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling reverseGeocodeApiV1RoutesReverseGeocodePost().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling reverseGeocodeApiV1RoutesReverseGeocodePost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/routes/reverse-geocode`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Convert coordinates to address.  Useful for displaying readable location names.
     * Reverse Geocode
     */
    async reverseGeocodeApiV1RoutesReverseGeocodePostRaw(requestParameters: ReverseGeocodeApiV1RoutesReverseGeocodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.reverseGeocodeApiV1RoutesReverseGeocodePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Convert coordinates to address.  Useful for displaying readable location names.
     * Reverse Geocode
     */
    async reverseGeocodeApiV1RoutesReverseGeocodePost(requestParameters: ReverseGeocodeApiV1RoutesReverseGeocodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.reverseGeocodeApiV1RoutesReverseGeocodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for routeOnlyApiV1RoutesRoutePost without sending the request
     */
    async routeOnlyApiV1RoutesRoutePostRequestOpts(requestParameters: RouteOnlyApiV1RoutesRoutePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['routeOnlyRequest'] == null) {
            throw new runtime.RequiredError(
                'routeOnlyRequest',
                'Required parameter "routeOnlyRequest" was null or undefined when calling routeOnlyApiV1RoutesRoutePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/routes/route`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RouteOnlyRequestToJSON(requestParameters['routeOnlyRequest']),
        };
    }

    /**
     * Phase 8.2: AMap routing only — polyline + distance + duration.  No POI search, no charging plan. iOS calls this first, then runs AMap SDK along-route POI search locally, then POSTs candidate POIs back to /routes/charging-plan to compute the greedy stops.
     * Route Only
     */
    async routeOnlyApiV1RoutesRoutePostRaw(requestParameters: RouteOnlyApiV1RoutesRoutePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RouteOnlyResponse>> {
        const requestOptions = await this.routeOnlyApiV1RoutesRoutePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RouteOnlyResponseFromJSON(jsonValue));
    }

    /**
     * Phase 8.2: AMap routing only — polyline + distance + duration.  No POI search, no charging plan. iOS calls this first, then runs AMap SDK along-route POI search locally, then POSTs candidate POIs back to /routes/charging-plan to compute the greedy stops.
     * Route Only
     */
    async routeOnlyApiV1RoutesRoutePost(requestParameters: RouteOnlyApiV1RoutesRoutePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RouteOnlyResponse> {
        const response = await this.routeOnlyApiV1RoutesRoutePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for searchPlacesApiV1RoutesSearchGet without sending the request
     */
    async searchPlacesApiV1RoutesSearchGetRequestOpts(requestParameters: SearchPlacesApiV1RoutesSearchGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['keyword'] == null) {
            throw new runtime.RequiredError(
                'keyword',
                'Required parameter "keyword" was null or undefined when calling searchPlacesApiV1RoutesSearchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['keyword'] != null) {
            queryParameters['keyword'] = requestParameters['keyword'];
        }

        if (requestParameters['location'] != null) {
            queryParameters['location'] = requestParameters['location'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/routes/search`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Search for places by keyword.  Args:     keyword: Search keyword (e.g., city name, POI name)     location: Optional center location \"lat,lng\" for distance calculation  Returns:     List of matching places with name, address, location and distance
     * Search Places
     */
    async searchPlacesApiV1RoutesSearchGetRaw(requestParameters: SearchPlacesApiV1RoutesSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.searchPlacesApiV1RoutesSearchGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Search for places by keyword.  Args:     keyword: Search keyword (e.g., city name, POI name)     location: Optional center location \"lat,lng\" for distance calculation  Returns:     List of matching places with name, address, location and distance
     * Search Places
     */
    async searchPlacesApiV1RoutesSearchGet(requestParameters: SearchPlacesApiV1RoutesSearchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.searchPlacesApiV1RoutesSearchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
