/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.apis.ChargingApi
import cloud.teplanner.api.models.ChargingStation
import cloud.teplanner.api.models.HTTPValidationError
import cloud.teplanner.api.models.StationSearchResponse

class ChargingApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChargingApi
        //val apiInstance = ChargingApi()

        // to test getStationApiV1ChargingStationsStationIdGet
        should("test getStationApiV1ChargingStationsStationIdGet") {
            // uncomment below to test getStationApiV1ChargingStationsStationIdGet
            //val stationId : kotlin.String = stationId_example // kotlin.String | 
            //val result : ChargingStation = apiInstance.getStationApiV1ChargingStationsStationIdGet(stationId)
            //result shouldBe ("TODO")
        }

        // to test searchNearbyStationsApiV1ChargingNearbyGet
        should("test searchNearbyStationsApiV1ChargingNearbyGet") {
            // uncomment below to test searchNearbyStationsApiV1ChargingNearbyGet
            //val latitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 中心点纬度
            //val longitude : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 中心点经度
            //val type : kotlin.String = type_example // kotlin.String | 类型: supercharger/destination/service/all
            //val radius : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 搜索半径(公里)
            //val result : StationSearchResponse = apiInstance.searchNearbyStationsApiV1ChargingNearbyGet(latitude, longitude, type, radius)
            //result shouldBe ("TODO")
        }

        // to test searchStationsApiV1ChargingStationsGet
        should("test searchStationsApiV1ChargingStationsGet") {
            // uncomment below to test searchStationsApiV1ChargingStationsGet
            //val lat : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 中心点纬度
            //val lng : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 中心点经度
            //val radiusKm : java.math.BigDecimal = 8.14 // java.math.BigDecimal | 搜索半径(公里)
            //val minPowerKw : kotlin.Int = 56 // kotlin.Int | 最小充电功率(kW)
            //val `operator` : kotlin.String = `operator`_example // kotlin.String | 运营商筛选
            //val result : StationSearchResponse = apiInstance.searchStationsApiV1ChargingStationsGet(lat, lng, radiusKm, minPowerKw, `operator`)
            //result shouldBe ("TODO")
        }

    }
}
