/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.apis.DefaultApi
import cloud.teplanner.api.models.HTTPValidationError

class DefaultApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DefaultApi
        //val apiInstance = DefaultApi()

        // to test healthCheckHealthGet
        should("test healthCheckHealthGet") {
            // uncomment below to test healthCheckHealthGet
            //val result : kotlin.Any = apiInstance.healthCheckHealthGet()
            //result shouldBe ("TODO")
        }

        // to test rootGet
        should("test rootGet") {
            // uncomment below to test rootGet
            //val result : kotlin.Any = apiInstance.rootGet()
            //result shouldBe ("TODO")
        }

        // to test serveWechatVerificationFilenameGet
        should("test serveWechatVerificationFilenameGet") {
            // uncomment below to test serveWechatVerificationFilenameGet
            //val filename : kotlin.String = filename_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.serveWechatVerificationFilenameGet(filename)
            //result shouldBe ("TODO")
        }

    }
}
