/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.apis.DevicesApi
import cloud.teplanner.api.models.HTTPValidationError
import cloud.teplanner.api.models.RegisterDeviceRequest
import cloud.teplanner.api.models.RegisterDeviceResponse
import cloud.teplanner.api.models.TestPushRequest

class DevicesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DevicesApi
        //val apiInstance = DevicesApi()

        // to test registerDeviceApiV1DevicesRegisterPost
        should("test registerDeviceApiV1DevicesRegisterPost") {
            // uncomment below to test registerDeviceApiV1DevicesRegisterPost
            //val registerDeviceRequest : RegisterDeviceRequest =  // RegisterDeviceRequest | 
            //val result : RegisterDeviceResponse = apiInstance.registerDeviceApiV1DevicesRegisterPost(registerDeviceRequest)
            //result shouldBe ("TODO")
        }

        // to test runAutomationTickApiV1DevicesRunAutomationTickPost
        should("test runAutomationTickApiV1DevicesRunAutomationTickPost") {
            // uncomment below to test runAutomationTickApiV1DevicesRunAutomationTickPost
            //val result : kotlin.Any = apiInstance.runAutomationTickApiV1DevicesRunAutomationTickPost()
            //result shouldBe ("TODO")
        }

        // to test testPushApiV1DevicesTestPushPost
        should("test testPushApiV1DevicesTestPushPost") {
            // uncomment below to test testPushApiV1DevicesTestPushPost
            //val testPushRequest : TestPushRequest =  // TestPushRequest | 
            //val result : kotlin.Any = apiInstance.testPushApiV1DevicesTestPushPost(testPushRequest)
            //result shouldBe ("TODO")
        }

    }
}
