/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.apis.UserApi
import cloud.teplanner.api.models.HTTPValidationError
import cloud.teplanner.api.models.ScheduledDepartureRequest
import cloud.teplanner.api.models.ScheduledDepartureResponse
import cloud.teplanner.api.models.UserSettingsRequest
import cloud.teplanner.api.models.UserSettingsResponse

class UserApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserApi
        //val apiInstance = UserApi()

        // to test clearScheduledDepartureApiV1UserScheduledDepartureDelete
        should("test clearScheduledDepartureApiV1UserScheduledDepartureDelete") {
            // uncomment below to test clearScheduledDepartureApiV1UserScheduledDepartureDelete
            //val result : kotlin.Any = apiInstance.clearScheduledDepartureApiV1UserScheduledDepartureDelete()
            //result shouldBe ("TODO")
        }

        // to test getScheduledDepartureApiV1UserScheduledDepartureGet
        should("test getScheduledDepartureApiV1UserScheduledDepartureGet") {
            // uncomment below to test getScheduledDepartureApiV1UserScheduledDepartureGet
            //val result : ScheduledDepartureResponse = apiInstance.getScheduledDepartureApiV1UserScheduledDepartureGet()
            //result shouldBe ("TODO")
        }

        // to test getUserSettingsApiV1UserSettingsGet
        should("test getUserSettingsApiV1UserSettingsGet") {
            // uncomment below to test getUserSettingsApiV1UserSettingsGet
            //val result : UserSettingsResponse = apiInstance.getUserSettingsApiV1UserSettingsGet()
            //result shouldBe ("TODO")
        }

        // to test upsertScheduledDepartureApiV1UserScheduledDeparturePut
        should("test upsertScheduledDepartureApiV1UserScheduledDeparturePut") {
            // uncomment below to test upsertScheduledDepartureApiV1UserScheduledDeparturePut
            //val scheduledDepartureRequest : ScheduledDepartureRequest =  // ScheduledDepartureRequest | 
            //val result : ScheduledDepartureResponse = apiInstance.upsertScheduledDepartureApiV1UserScheduledDeparturePut(scheduledDepartureRequest)
            //result shouldBe ("TODO")
        }

        // to test upsertUserSettingsApiV1UserSettingsPut
        should("test upsertUserSettingsApiV1UserSettingsPut") {
            // uncomment below to test upsertUserSettingsApiV1UserSettingsPut
            //val userSettingsRequest : UserSettingsRequest =  // UserSettingsRequest | 
            //val result : UserSettingsResponse = apiInstance.upsertUserSettingsApiV1UserSettingsPut(userSettingsRequest)
            //result shouldBe ("TODO")
        }

    }
}
