/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import cloud.teplanner.api.apis.VehiclesApi
import cloud.teplanner.api.models.ChargeLimitRequest
import cloud.teplanner.api.models.ChargingSessionListResponse
import cloud.teplanner.api.models.ChargingSessionRequest
import cloud.teplanner.api.models.ChargingSessionResponse
import cloud.teplanner.api.models.ClimateKeeperModeRequest
import cloud.teplanner.api.models.HTTPValidationError
import cloud.teplanner.api.models.NavigationAddressRequest
import cloud.teplanner.api.models.NavigationRequest
import cloud.teplanner.api.models.PendingCommandListResponse
import cloud.teplanner.api.models.QueuedCommandListResponse
import cloud.teplanner.api.models.SentryModeRequest
import cloud.teplanner.api.models.SuggestChargeLimitRequest
import cloud.teplanner.api.models.SuggestChargeLimitResponse
import cloud.teplanner.api.models.VehicleListResponse
import cloud.teplanner.api.models.VehicleResponse
import cloud.teplanner.api.models.VehicleStateResponse
import cloud.teplanner.api.models.WakeResponse

class VehiclesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of VehiclesApi
        //val apiInstance = VehiclesApi()

        // to test cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDelete
        should("test cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDelete") {
            // uncomment below to test cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDelete
            //val queuedId : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.Any = apiInstance.cancelQueuedCommandApiV1VehiclesCommandsQueuedQueuedIdDelete(queuedId)
            //result shouldBe ("TODO")
        }

        // to test getVehicleApiV1VehiclesVehicleIdGet
        should("test getVehicleApiV1VehiclesVehicleIdGet") {
            // uncomment below to test getVehicleApiV1VehiclesVehicleIdGet
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val result : VehicleResponse = apiInstance.getVehicleApiV1VehiclesVehicleIdGet(vehicleId)
            //result shouldBe ("TODO")
        }

        // to test getVehicleStateApiV1VehiclesVehicleIdStateGet
        should("test getVehicleStateApiV1VehiclesVehicleIdStateGet") {
            // uncomment below to test getVehicleStateApiV1VehiclesVehicleIdStateGet
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val result : VehicleStateResponse = apiInstance.getVehicleStateApiV1VehiclesVehicleIdStateGet(vehicleId)
            //result shouldBe ("TODO")
        }

        // to test listChargingSessionsApiV1VehiclesVehicleIdSessionsGet
        should("test listChargingSessionsApiV1VehiclesVehicleIdSessionsGet") {
            // uncomment below to test listChargingSessionsApiV1VehiclesVehicleIdSessionsGet
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : ChargingSessionListResponse = apiInstance.listChargingSessionsApiV1VehiclesVehicleIdSessionsGet(vehicleId, limit)
            //result shouldBe ("TODO")
        }

        // to test listPendingCommandsApiV1VehiclesCommandsPendingGet
        should("test listPendingCommandsApiV1VehiclesCommandsPendingGet") {
            // uncomment below to test listPendingCommandsApiV1VehiclesCommandsPendingGet
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : PendingCommandListResponse = apiInstance.listPendingCommandsApiV1VehiclesCommandsPendingGet(limit)
            //result shouldBe ("TODO")
        }

        // to test listQueuedCommandsApiV1VehiclesCommandsQueuedGet
        should("test listQueuedCommandsApiV1VehiclesCommandsQueuedGet") {
            // uncomment below to test listQueuedCommandsApiV1VehiclesCommandsQueuedGet
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : QueuedCommandListResponse = apiInstance.listQueuedCommandsApiV1VehiclesCommandsQueuedGet(limit)
            //result shouldBe ("TODO")
        }

        // to test listVehiclesApiV1VehiclesGet
        should("test listVehiclesApiV1VehiclesGet") {
            // uncomment below to test listVehiclesApiV1VehiclesGet
            //val result : VehicleListResponse = apiInstance.listVehiclesApiV1VehiclesGet()
            //result shouldBe ("TODO")
        }

        // to test navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPost
        should("test navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPost") {
            // uncomment below to test navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val navigationAddressRequest : NavigationAddressRequest =  // NavigationAddressRequest | 
            //val result : kotlin.Any = apiInstance.navigateVehicleAddressApiV1VehiclesVehicleIdNavigateAddressPost(vehicleId, navigationAddressRequest)
            //result shouldBe ("TODO")
        }

        // to test navigateVehicleApiV1VehiclesVehicleIdNavigatePost
        should("test navigateVehicleApiV1VehiclesVehicleIdNavigatePost") {
            // uncomment below to test navigateVehicleApiV1VehiclesVehicleIdNavigatePost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val navigationRequest : NavigationRequest =  // NavigationRequest | 
            //val result : kotlin.Any = apiInstance.navigateVehicleApiV1VehiclesVehicleIdNavigatePost(vehicleId, navigationRequest)
            //result shouldBe ("TODO")
        }

        // to test preheatVehicleApiV1VehiclesVehicleIdPreheatPost
        should("test preheatVehicleApiV1VehiclesVehicleIdPreheatPost") {
            // uncomment below to test preheatVehicleApiV1VehiclesVehicleIdPreheatPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.preheatVehicleApiV1VehiclesVehicleIdPreheatPost(vehicleId)
            //result shouldBe ("TODO")
        }

        // to test setChargeLimitApiV1VehiclesVehicleIdChargeLimitPost
        should("test setChargeLimitApiV1VehiclesVehicleIdChargeLimitPost") {
            // uncomment below to test setChargeLimitApiV1VehiclesVehicleIdChargeLimitPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val chargeLimitRequest : ChargeLimitRequest =  // ChargeLimitRequest | 
            //val result : kotlin.Any = apiInstance.setChargeLimitApiV1VehiclesVehicleIdChargeLimitPost(vehicleId, chargeLimitRequest)
            //result shouldBe ("TODO")
        }

        // to test setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePost
        should("test setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePost") {
            // uncomment below to test setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val climateKeeperModeRequest : ClimateKeeperModeRequest =  // ClimateKeeperModeRequest | 
            //val result : kotlin.Any = apiInstance.setClimateKeeperModeApiV1VehiclesVehicleIdClimateKeeperModePost(vehicleId, climateKeeperModeRequest)
            //result shouldBe ("TODO")
        }

        // to test setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPost
        should("test setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPost") {
            // uncomment below to test setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val result : kotlin.Any = apiInstance.setPrimaryVehicleApiV1VehiclesVehicleIdSetPrimaryPost(vehicleId)
            //result shouldBe ("TODO")
        }

        // to test setSentryModeApiV1VehiclesVehicleIdSentryModePost
        should("test setSentryModeApiV1VehiclesVehicleIdSentryModePost") {
            // uncomment below to test setSentryModeApiV1VehiclesVehicleIdSentryModePost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val sentryModeRequest : SentryModeRequest =  // SentryModeRequest | 
            //val result : kotlin.Any = apiInstance.setSentryModeApiV1VehiclesVehicleIdSentryModePost(vehicleId, sentryModeRequest)
            //result shouldBe ("TODO")
        }

        // to test suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPost
        should("test suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPost") {
            // uncomment below to test suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val suggestChargeLimitRequest : SuggestChargeLimitRequest =  // SuggestChargeLimitRequest | 
            //val result : SuggestChargeLimitResponse = apiInstance.suggestChargeLimitEndpointApiV1VehiclesVehicleIdSuggestChargeLimitPost(vehicleId, suggestChargeLimitRequest)
            //result shouldBe ("TODO")
        }

        // to test upsertChargingSessionApiV1VehiclesVehicleIdSessionsPost
        should("test upsertChargingSessionApiV1VehiclesVehicleIdSessionsPost") {
            // uncomment below to test upsertChargingSessionApiV1VehiclesVehicleIdSessionsPost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val chargingSessionRequest : ChargingSessionRequest =  // ChargingSessionRequest | 
            //val result : ChargingSessionResponse = apiInstance.upsertChargingSessionApiV1VehiclesVehicleIdSessionsPost(vehicleId, chargingSessionRequest)
            //result shouldBe ("TODO")
        }

        // to test wakeVehicleApiV1VehiclesVehicleIdWakePost
        should("test wakeVehicleApiV1VehiclesVehicleIdWakePost") {
            // uncomment below to test wakeVehicleApiV1VehiclesVehicleIdWakePost
            //val vehicleId : kotlin.String = vehicleId_example // kotlin.String | 
            //val result : WakeResponse = apiInstance.wakeVehicleApiV1VehiclesVehicleIdWakePost(vehicleId)
            //result shouldBe ("TODO")
        }

    }
}
