/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Charging stop in route.
 * @export
 * @interface ChargingStopResponse
 */
export interface ChargingStopResponse {
    /**
     * 
     * @type {string}
     * @memberof ChargingStopResponse
     */
    station_id: string;
    /**
     * 
     * @type {string}
     * @memberof ChargingStopResponse
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof ChargingStopResponse
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChargingStopResponse
     */
    operator?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    distance_from_start_km: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    arrival_soc: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    departure_soc: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingStopResponse
     */
    charging_duration_minutes: number;
}

/**
 * Check if a given object implements the ChargingStopResponse interface.
 */
export function instanceOfChargingStopResponse(value: object): value is ChargingStopResponse {
    if (!('station_id' in value) || value['station_id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('distance_from_start_km' in value) || value['distance_from_start_km'] === undefined) return false;
    if (!('arrival_soc' in value) || value['arrival_soc'] === undefined) return false;
    if (!('departure_soc' in value) || value['departure_soc'] === undefined) return false;
    if (!('charging_duration_minutes' in value) || value['charging_duration_minutes'] === undefined) return false;
    return true;
}

export function ChargingStopResponseFromJSON(json: any): ChargingStopResponse {
    return ChargingStopResponseFromJSONTyped(json, false);
}

export function ChargingStopResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargingStopResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'station_id': json['station_id'],
        'name': json['name'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'address': json['address'] == null ? undefined : json['address'],
        'operator': json['operator'] == null ? undefined : json['operator'],
        'distance_from_start_km': json['distance_from_start_km'],
        'arrival_soc': json['arrival_soc'],
        'departure_soc': json['departure_soc'],
        'charging_duration_minutes': json['charging_duration_minutes'],
    };
}

export function ChargingStopResponseToJSON(json: any): ChargingStopResponse {
    return ChargingStopResponseToJSONTyped(json, false);
}

export function ChargingStopResponseToJSONTyped(value?: ChargingStopResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'station_id': value['station_id'],
        'name': value['name'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'address': value['address'],
        'operator': value['operator'],
        'distance_from_start_km': value['distance_from_start_km'],
        'arrival_soc': value['arrival_soc'],
        'departure_soc': value['departure_soc'],
        'charging_duration_minutes': value['charging_duration_minutes'],
    };
}

