/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChargingSessionRequest
 */
export interface ChargingSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionRequest
     */
    client_session_id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    end_range_km?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    end_soc?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChargingSessionRequest
     */
    ended_as_complete?: boolean | null;
    /**
     * 
     * @type {Date}
     * @memberof ChargingSessionRequest
     */
    ended_at?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    energy_added_kwh?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    lat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    lng?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionRequest
     */
    location_name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    start_range_km?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionRequest
     */
    start_soc?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChargingSessionRequest
     */
    started_at: Date;
}

/**
 * Check if a given object implements the ChargingSessionRequest interface.
 */
export function instanceOfChargingSessionRequest(value: object): value is ChargingSessionRequest {
    if (!('started_at' in value) || value['started_at'] === undefined) return false;
    return true;
}

export function ChargingSessionRequestFromJSON(json: any): ChargingSessionRequest {
    return ChargingSessionRequestFromJSONTyped(json, false);
}

export function ChargingSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargingSessionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'client_session_id': json['client_session_id'] == null ? undefined : json['client_session_id'],
        'end_range_km': json['end_range_km'] == null ? undefined : json['end_range_km'],
        'end_soc': json['end_soc'] == null ? undefined : json['end_soc'],
        'ended_as_complete': json['ended_as_complete'] == null ? undefined : json['ended_as_complete'],
        'ended_at': json['ended_at'] == null ? undefined : (new Date(json['ended_at'])),
        'energy_added_kwh': json['energy_added_kwh'] == null ? undefined : json['energy_added_kwh'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
        'location_name': json['location_name'] == null ? undefined : json['location_name'],
        'start_range_km': json['start_range_km'] == null ? undefined : json['start_range_km'],
        'start_soc': json['start_soc'] == null ? undefined : json['start_soc'],
        'started_at': (new Date(json['started_at'])),
    };
}

export function ChargingSessionRequestToJSON(json: any): ChargingSessionRequest {
    return ChargingSessionRequestToJSONTyped(json, false);
}

export function ChargingSessionRequestToJSONTyped(value?: ChargingSessionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_session_id': value['client_session_id'],
        'end_range_km': value['end_range_km'],
        'end_soc': value['end_soc'],
        'ended_as_complete': value['ended_as_complete'],
        'ended_at': value['ended_at'] == null ? value['ended_at'] : value['ended_at'].toISOString(),
        'energy_added_kwh': value['energy_added_kwh'],
        'lat': value['lat'],
        'lng': value['lng'],
        'location_name': value['location_name'],
        'start_range_km': value['start_range_km'],
        'start_soc': value['start_soc'],
        'started_at': value['started_at'].toISOString(),
    };
}

