/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Set the charge limit SOC percent (50..100).
 * @export
 * @interface ChargeLimitRequest
 */
export interface ChargeLimitRequest {
    /**
     * 
     * @type {number}
     * @memberof ChargeLimitRequest
     */
    percent: number;
}

/**
 * Check if a given object implements the ChargeLimitRequest interface.
 */
export function instanceOfChargeLimitRequest(value: object): value is ChargeLimitRequest {
    if (!('percent' in value) || value['percent'] === undefined) return false;
    return true;
}

export function ChargeLimitRequestFromJSON(json: any): ChargeLimitRequest {
    return ChargeLimitRequestFromJSONTyped(json, false);
}

export function ChargeLimitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargeLimitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'percent': json['percent'],
    };
}

export function ChargeLimitRequestToJSON(json: any): ChargeLimitRequest {
    return ChargeLimitRequestToJSONTyped(json, false);
}

export function ChargeLimitRequestToJSONTyped(value?: ChargeLimitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'percent': value['percent'],
    };
}

