/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChargingSessionResponse
 */
export interface ChargingSessionResponse {
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionResponse
     */
    vehicle_id: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionResponse
     */
    client_session_id: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ChargingSessionResponse
     */
    started_at: Date;
    /**
     * 
     * @type {Date}
     * @memberof ChargingSessionResponse
     */
    ended_at: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    start_soc: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    end_soc: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    start_range_km: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    end_range_km: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    energy_added_kwh: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionResponse
     */
    location_name: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    lat: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    lng: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChargingSessionResponse
     */
    ended_as_complete: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof ChargingSessionResponse
     */
    source: string;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    duration_minutes: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    range_added_km: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChargingSessionResponse
     */
    soc_delta: number | null;
}

/**
 * Check if a given object implements the ChargingSessionResponse interface.
 */
export function instanceOfChargingSessionResponse(value: object): value is ChargingSessionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('vehicle_id' in value) || value['vehicle_id'] === undefined) return false;
    if (!('client_session_id' in value) || value['client_session_id'] === undefined) return false;
    if (!('started_at' in value) || value['started_at'] === undefined) return false;
    if (!('ended_at' in value) || value['ended_at'] === undefined) return false;
    if (!('start_soc' in value) || value['start_soc'] === undefined) return false;
    if (!('end_soc' in value) || value['end_soc'] === undefined) return false;
    if (!('start_range_km' in value) || value['start_range_km'] === undefined) return false;
    if (!('end_range_km' in value) || value['end_range_km'] === undefined) return false;
    if (!('energy_added_kwh' in value) || value['energy_added_kwh'] === undefined) return false;
    if (!('location_name' in value) || value['location_name'] === undefined) return false;
    if (!('lat' in value) || value['lat'] === undefined) return false;
    if (!('lng' in value) || value['lng'] === undefined) return false;
    if (!('ended_as_complete' in value) || value['ended_as_complete'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('duration_minutes' in value) || value['duration_minutes'] === undefined) return false;
    if (!('range_added_km' in value) || value['range_added_km'] === undefined) return false;
    if (!('soc_delta' in value) || value['soc_delta'] === undefined) return false;
    return true;
}

export function ChargingSessionResponseFromJSON(json: any): ChargingSessionResponse {
    return ChargingSessionResponseFromJSONTyped(json, false);
}

export function ChargingSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargingSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'vehicle_id': json['vehicle_id'],
        'client_session_id': json['client_session_id'],
        'started_at': (new Date(json['started_at'])),
        'ended_at': (json['ended_at'] == null ? null : new Date(json['ended_at'])),
        'start_soc': json['start_soc'],
        'end_soc': json['end_soc'],
        'start_range_km': json['start_range_km'],
        'end_range_km': json['end_range_km'],
        'energy_added_kwh': json['energy_added_kwh'],
        'location_name': json['location_name'],
        'lat': json['lat'],
        'lng': json['lng'],
        'ended_as_complete': json['ended_as_complete'],
        'source': json['source'],
        'duration_minutes': json['duration_minutes'],
        'range_added_km': json['range_added_km'],
        'soc_delta': json['soc_delta'],
    };
}

export function ChargingSessionResponseToJSON(json: any): ChargingSessionResponse {
    return ChargingSessionResponseToJSONTyped(json, false);
}

export function ChargingSessionResponseToJSONTyped(value?: ChargingSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'vehicle_id': value['vehicle_id'],
        'client_session_id': value['client_session_id'],
        'started_at': value['started_at'].toISOString(),
        'ended_at': value['ended_at'] == null ? value['ended_at'] : value['ended_at'].toISOString(),
        'start_soc': value['start_soc'],
        'end_soc': value['end_soc'],
        'start_range_km': value['start_range_km'],
        'end_range_km': value['end_range_km'],
        'energy_added_kwh': value['energy_added_kwh'],
        'location_name': value['location_name'],
        'lat': value['lat'],
        'lng': value['lng'],
        'ended_as_complete': value['ended_as_complete'],
        'source': value['source'],
        'duration_minutes': value['duration_minutes'],
        'range_added_km': value['range_added_km'],
        'soc_delta': value['soc_delta'],
    };
}

