/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChargingStopResponse } from './ChargingStopResponse';
import {
    ChargingStopResponseFromJSON,
    ChargingStopResponseFromJSONTyped,
    ChargingStopResponseToJSON,
    ChargingStopResponseToJSONTyped,
} from './ChargingStopResponse';

/**
 * Output: just the charging-related fields. The iOS client merges
 * this with the previously-fetched route data to produce its
 * RoutePlanResponse-shape view model.
 * @export
 * @interface ChargingPlanResponse
 */
export interface ChargingPlanResponse {
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanResponse
     */
    arrival_soc: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanResponse
     */
    charging_duration_minutes: number;
    /**
     * 
     * @type {Array<ChargingStopResponse>}
     * @memberof ChargingPlanResponse
     */
    charging_stops: Array<ChargingStopResponse>;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanResponse
     */
    num_charging_stops: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ChargingPlanResponse
     */
    warnings?: Array<string>;
}

/**
 * Check if a given object implements the ChargingPlanResponse interface.
 */
export function instanceOfChargingPlanResponse(value: object): value is ChargingPlanResponse {
    if (!('arrival_soc' in value) || value['arrival_soc'] === undefined) return false;
    if (!('charging_duration_minutes' in value) || value['charging_duration_minutes'] === undefined) return false;
    if (!('charging_stops' in value) || value['charging_stops'] === undefined) return false;
    if (!('num_charging_stops' in value) || value['num_charging_stops'] === undefined) return false;
    return true;
}

export function ChargingPlanResponseFromJSON(json: any): ChargingPlanResponse {
    return ChargingPlanResponseFromJSONTyped(json, false);
}

export function ChargingPlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargingPlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'arrival_soc': json['arrival_soc'],
        'charging_duration_minutes': json['charging_duration_minutes'],
        'charging_stops': ((json['charging_stops'] as Array<any>).map(ChargingStopResponseFromJSON)),
        'num_charging_stops': json['num_charging_stops'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function ChargingPlanResponseToJSON(json: any): ChargingPlanResponse {
    return ChargingPlanResponseToJSONTyped(json, false);
}

export function ChargingPlanResponseToJSONTyped(value?: ChargingPlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'arrival_soc': value['arrival_soc'],
        'charging_duration_minutes': value['charging_duration_minutes'],
        'charging_stops': ((value['charging_stops'] as Array<any>).map(ChargingStopResponseToJSON)),
        'num_charging_stops': value['num_charging_stops'],
        'warnings': value['warnings'],
    };
}

