/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { POIInput } from './POIInput';
import {
    POIInputFromJSON,
    POIInputFromJSONTyped,
    POIInputToJSON,
    POIInputToJSONTyped,
} from './POIInput';

/**
 * Phase 8.2: greedy charging-stop selection over client-provided
 * POIs. The iOS client gathers POIs via AMap SDK along-route search
 * (proper road corridor) and posts them here.
 * @export
 * @interface ChargingPlanRequest
 */
export interface ChargingPlanRequest {
    /**
     * [[lat, lng], …]
     * @type {Array<Array<number>>}
     * @memberof ChargingPlanRequest
     */
    polyline: Array<Array<number>>;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanRequest
     */
    total_distance_km: number;
    /**
     * 
     * @type {Array<POIInput>}
     * @memberof ChargingPlanRequest
     */
    candidate_pois: Array<POIInput>;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanRequest
     */
    initial_soc: number;
    /**
     * 
     * @type {string}
     * @memberof ChargingPlanRequest
     */
    car_type?: string;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanRequest
     */
    min_arrival_soc?: number;
    /**
     * 
     * @type {number}
     * @memberof ChargingPlanRequest
     */
    vehicle_range_km?: number | null;
}

/**
 * Check if a given object implements the ChargingPlanRequest interface.
 */
export function instanceOfChargingPlanRequest(value: object): value is ChargingPlanRequest {
    if (!('polyline' in value) || value['polyline'] === undefined) return false;
    if (!('total_distance_km' in value) || value['total_distance_km'] === undefined) return false;
    if (!('candidate_pois' in value) || value['candidate_pois'] === undefined) return false;
    if (!('initial_soc' in value) || value['initial_soc'] === undefined) return false;
    return true;
}

export function ChargingPlanRequestFromJSON(json: any): ChargingPlanRequest {
    return ChargingPlanRequestFromJSONTyped(json, false);
}

export function ChargingPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChargingPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'polyline': json['polyline'],
        'total_distance_km': json['total_distance_km'],
        'candidate_pois': ((json['candidate_pois'] as Array<any>).map(POIInputFromJSON)),
        'initial_soc': json['initial_soc'],
        'car_type': json['car_type'] == null ? undefined : json['car_type'],
        'min_arrival_soc': json['min_arrival_soc'] == null ? undefined : json['min_arrival_soc'],
        'vehicle_range_km': json['vehicle_range_km'] == null ? undefined : json['vehicle_range_km'],
    };
}

export function ChargingPlanRequestToJSON(json: any): ChargingPlanRequest {
    return ChargingPlanRequestToJSONTyped(json, false);
}

export function ChargingPlanRequestToJSONTyped(value?: ChargingPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polyline': value['polyline'],
        'total_distance_km': value['total_distance_km'],
        'candidate_pois': ((value['candidate_pois'] as Array<any>).map(POIInputToJSON)),
        'initial_soc': value['initial_soc'],
        'car_type': value['car_type'],
        'min_arrival_soc': value['min_arrival_soc'],
        'vehicle_range_km': value['vehicle_range_km'],
    };
}

