/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Email registration request.
 * @export
 * @interface EmailRegisterRequest
 */
export interface EmailRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof EmailRegisterRequest
     */
    nickname?: string | null;
}

/**
 * Check if a given object implements the EmailRegisterRequest interface.
 */
export function instanceOfEmailRegisterRequest(value: object): value is EmailRegisterRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function EmailRegisterRequestFromJSON(json: any): EmailRegisterRequest {
    return EmailRegisterRequestFromJSONTyped(json, false);
}

export function EmailRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
    };
}

export function EmailRegisterRequestToJSON(json: any): EmailRegisterRequest {
    return EmailRegisterRequestToJSONTyped(json, false);
}

export function EmailRegisterRequestToJSONTyped(value?: EmailRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'nickname': value['nickname'],
    };
}

