/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Email login request.
 * @export
 * @interface EmailLoginRequest
 */
export interface EmailLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailLoginRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the EmailLoginRequest interface.
 */
export function instanceOfEmailLoginRequest(value: object): value is EmailLoginRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function EmailLoginRequestFromJSON(json: any): EmailLoginRequest {
    return EmailLoginRequestFromJSONTyped(json, false);
}

export function EmailLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function EmailLoginRequestToJSON(json: any): EmailLoginRequest {
    return EmailLoginRequestToJSONTyped(json, false);
}

export function EmailLoginRequestToJSONTyped(value?: EmailLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

