/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Email auth response.
 * @export
 * @interface EmailAuthResponse
 */
export interface EmailAuthResponse {
    /**
     * 
     * @type {string}
     * @memberof EmailAuthResponse
     */
    access_token: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAuthResponse
     */
    token_type?: string;
    /**
     * 
     * @type {number}
     * @memberof EmailAuthResponse
     */
    expires_in: number;
    /**
     * 
     * @type {number}
     * @memberof EmailAuthResponse
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof EmailAuthResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailAuthResponse
     */
    nickname?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EmailAuthResponse
     */
    has_tesla_linked?: boolean;
}

/**
 * Check if a given object implements the EmailAuthResponse interface.
 */
export function instanceOfEmailAuthResponse(value: object): value is EmailAuthResponse {
    if (!('access_token' in value) || value['access_token'] === undefined) return false;
    if (!('expires_in' in value) || value['expires_in'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function EmailAuthResponseFromJSON(json: any): EmailAuthResponse {
    return EmailAuthResponseFromJSONTyped(json, false);
}

export function EmailAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailAuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
        'expires_in': json['expires_in'],
        'user_id': json['user_id'],
        'email': json['email'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'has_tesla_linked': json['has_tesla_linked'] == null ? undefined : json['has_tesla_linked'],
    };
}

export function EmailAuthResponseToJSON(json: any): EmailAuthResponse {
    return EmailAuthResponseToJSONTyped(json, false);
}

export function EmailAuthResponseToJSONTyped(value?: EmailAuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['access_token'],
        'token_type': value['token_type'],
        'expires_in': value['expires_in'],
        'user_id': value['user_id'],
        'email': value['email'],
        'nickname': value['nickname'],
        'has_tesla_linked': value['has_tesla_linked'],
    };
}

