/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Navigation by address request model.
 * @export
 * @interface NavigationAddressRequest
 */
export interface NavigationAddressRequest {
    /**
     * 
     * @type {string}
     * @memberof NavigationAddressRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof NavigationAddressRequest
     */
    locale?: string;
}

/**
 * Check if a given object implements the NavigationAddressRequest interface.
 */
export function instanceOfNavigationAddressRequest(value: object): value is NavigationAddressRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function NavigationAddressRequestFromJSON(json: any): NavigationAddressRequest {
    return NavigationAddressRequestFromJSONTyped(json, false);
}

export function NavigationAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationAddressRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'locale': json['locale'] == null ? undefined : json['locale'],
    };
}

export function NavigationAddressRequestToJSON(json: any): NavigationAddressRequest {
    return NavigationAddressRequestToJSONTyped(json, false);
}

export function NavigationAddressRequestToJSONTyped(value?: NavigationAddressRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'locale': value['locale'],
    };
}

