/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocationInput } from './LocationInput';
import {
    LocationInputFromJSON,
    LocationInputFromJSONTyped,
    LocationInputToJSON,
    LocationInputToJSONTyped,
} from './LocationInput';

/**
 * Request to send route to vehicle.
 * @export
 * @interface NavigateRouteRequest
 */
export interface NavigateRouteRequest {
    /**
     * 
     * @type {string}
     * @memberof NavigateRouteRequest
     */
    vehicle_id: string;
    /**
     * 
     * @type {Array<LocationInput>}
     * @memberof NavigateRouteRequest
     */
    waypoints?: Array<LocationInput> | null;
}

/**
 * Check if a given object implements the NavigateRouteRequest interface.
 */
export function instanceOfNavigateRouteRequest(value: object): value is NavigateRouteRequest {
    if (!('vehicle_id' in value) || value['vehicle_id'] === undefined) return false;
    return true;
}

export function NavigateRouteRequestFromJSON(json: any): NavigateRouteRequest {
    return NavigateRouteRequestFromJSONTyped(json, false);
}

export function NavigateRouteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigateRouteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicle_id': json['vehicle_id'],
        'waypoints': json['waypoints'] == null ? undefined : ((json['waypoints'] as Array<any>).map(LocationInputFromJSON)),
    };
}

export function NavigateRouteRequestToJSON(json: any): NavigateRouteRequest {
    return NavigateRouteRequestToJSONTyped(json, false);
}

export function NavigateRouteRequestToJSONTyped(value?: NavigateRouteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicle_id': value['vehicle_id'],
        'waypoints': value['waypoints'] == null ? undefined : ((value['waypoints'] as Array<any>).map(LocationInputToJSON)),
    };
}

