/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Navigation request model.
 * @export
 * @interface NavigationRequest
 */
export interface NavigationRequest {
    /**
     * 
     * @type {number}
     * @memberof NavigationRequest
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof NavigationRequest
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof NavigationRequest
     */
    order?: number;
}

/**
 * Check if a given object implements the NavigationRequest interface.
 */
export function instanceOfNavigationRequest(value: object): value is NavigationRequest {
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function NavigationRequestFromJSON(json: any): NavigationRequest {
    return NavigationRequestFromJSONTyped(json, false);
}

export function NavigationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NavigationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function NavigationRequestToJSON(json: any): NavigationRequest {
    return NavigationRequestToJSONTyped(json, false);
}

export function NavigationRequestToJSONTyped(value?: NavigationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'order': value['order'],
    };
}

