/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PendingCommandResponse
 */
export interface PendingCommandResponse {
    /**
     * 
     * @type {string}
     * @memberof PendingCommandResponse
     */
    capability: string;
    /**
     * 
     * @type {Date}
     * @memberof PendingCommandResponse
     */
    confirmed_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PendingCommandResponse
     */
    dispatched_at: Date;
    /**
     * 
     * @type {object}
     * @memberof PendingCommandResponse
     */
    expected_state: object;
    /**
     * 
     * @type {number}
     * @memberof PendingCommandResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PendingCommandResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof PendingCommandResponse
     */
    timed_out_at?: Date | null;
}

/**
 * Check if a given object implements the PendingCommandResponse interface.
 */
export function instanceOfPendingCommandResponse(value: object): value is PendingCommandResponse {
    if (!('capability' in value) || value['capability'] === undefined) return false;
    if (!('dispatched_at' in value) || value['dispatched_at'] === undefined) return false;
    if (!('expected_state' in value) || value['expected_state'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PendingCommandResponseFromJSON(json: any): PendingCommandResponse {
    return PendingCommandResponseFromJSONTyped(json, false);
}

export function PendingCommandResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PendingCommandResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'capability': json['capability'],
        'confirmed_at': json['confirmed_at'] == null ? undefined : (new Date(json['confirmed_at'])),
        'dispatched_at': (new Date(json['dispatched_at'])),
        'expected_state': json['expected_state'],
        'id': json['id'],
        'status': json['status'],
        'timed_out_at': json['timed_out_at'] == null ? undefined : (new Date(json['timed_out_at'])),
    };
}

export function PendingCommandResponseToJSON(json: any): PendingCommandResponse {
    return PendingCommandResponseToJSONTyped(json, false);
}

export function PendingCommandResponseToJSONTyped(value?: PendingCommandResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'capability': value['capability'],
        'confirmed_at': value['confirmed_at'] == null ? value['confirmed_at'] : value['confirmed_at'].toISOString(),
        'dispatched_at': value['dispatched_at'].toISOString(),
        'expected_state': value['expected_state'],
        'id': value['id'],
        'status': value['status'],
        'timed_out_at': value['timed_out_at'] == null ? value['timed_out_at'] : value['timed_out_at'].toISOString(),
    };
}

