/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Candidate POI for the charging-plan endpoint. Shape mirrors
 * AMapRoutePOI (iOS SDK) — only id / name / lat / lng required.
 * @export
 * @interface POIInput
 */
export interface POIInput {
    /**
     * 
     * @type {string}
     * @memberof POIInput
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof POIInput
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof POIInput
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof POIInput
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof POIInput
     */
    name: string;
}

/**
 * Check if a given object implements the POIInput interface.
 */
export function instanceOfPOIInput(value: object): value is POIInput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function POIInputFromJSON(json: any): POIInput {
    return POIInputFromJSONTyped(json, false);
}

export function POIInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): POIInput {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'id': json['id'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'name': json['name'],
    };
}

export function POIInputToJSON(json: any): POIInput {
    return POIInputToJSONTyped(json, false);
}

export function POIInputToJSONTyped(value?: POIInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'id': value['id'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'name': value['name'],
    };
}

