/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueuedCommandResponse } from './QueuedCommandResponse';
import {
    QueuedCommandResponseFromJSON,
    QueuedCommandResponseFromJSONTyped,
    QueuedCommandResponseToJSON,
    QueuedCommandResponseToJSONTyped,
} from './QueuedCommandResponse';

/**
 * 
 * @export
 * @interface QueuedCommandListResponse
 */
export interface QueuedCommandListResponse {
    /**
     * 
     * @type {Array<QueuedCommandResponse>}
     * @memberof QueuedCommandListResponse
     */
    queued: Array<QueuedCommandResponse>;
}

/**
 * Check if a given object implements the QueuedCommandListResponse interface.
 */
export function instanceOfQueuedCommandListResponse(value: object): value is QueuedCommandListResponse {
    if (!('queued' in value) || value['queued'] === undefined) return false;
    return true;
}

export function QueuedCommandListResponseFromJSON(json: any): QueuedCommandListResponse {
    return QueuedCommandListResponseFromJSONTyped(json, false);
}

export function QueuedCommandListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueuedCommandListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'queued': ((json['queued'] as Array<any>).map(QueuedCommandResponseFromJSON)),
    };
}

export function QueuedCommandListResponseToJSON(json: any): QueuedCommandListResponse {
    return QueuedCommandListResponseToJSONTyped(json, false);
}

export function QueuedCommandListResponseToJSONTyped(value?: QueuedCommandListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queued': ((value['queued'] as Array<any>).map(QueuedCommandResponseToJSON)),
    };
}

