/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecentFireEntry
 */
export interface RecentFireEntry {
    /**
     * 
     * @type {Date}
     * @memberof RecentFireEntry
     */
    cleared_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RecentFireEntry
     */
    kind: string;
    /**
     * 
     * @type {Date}
     * @memberof RecentFireEntry
     */
    pushed_at: Date;
}

/**
 * Check if a given object implements the RecentFireEntry interface.
 */
export function instanceOfRecentFireEntry(value: object): value is RecentFireEntry {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('pushed_at' in value) || value['pushed_at'] === undefined) return false;
    return true;
}

export function RecentFireEntryFromJSON(json: any): RecentFireEntry {
    return RecentFireEntryFromJSONTyped(json, false);
}

export function RecentFireEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentFireEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'cleared_at': json['cleared_at'] == null ? undefined : (new Date(json['cleared_at'])),
        'kind': json['kind'],
        'pushed_at': (new Date(json['pushed_at'])),
    };
}

export function RecentFireEntryToJSON(json: any): RecentFireEntry {
    return RecentFireEntryToJSONTyped(json, false);
}

export function RecentFireEntryToJSONTyped(value?: RecentFireEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cleared_at': value['cleared_at'] == null ? value['cleared_at'] : value['cleared_at'].toISOString(),
        'kind': value['kind'],
        'pushed_at': value['pushed_at'].toISOString(),
    };
}

