/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecentFireEntry } from './RecentFireEntry';
import {
    RecentFireEntryFromJSON,
    RecentFireEntryFromJSONTyped,
    RecentFireEntryToJSON,
    RecentFireEntryToJSONTyped,
} from './RecentFireEntry';

/**
 * 
 * @export
 * @interface RecentFiresResponse
 */
export interface RecentFiresResponse {
    /**
     * 
     * @type {Array<RecentFireEntry>}
     * @memberof RecentFiresResponse
     */
    fires: Array<RecentFireEntry>;
}

/**
 * Check if a given object implements the RecentFiresResponse interface.
 */
export function instanceOfRecentFiresResponse(value: object): value is RecentFiresResponse {
    if (!('fires' in value) || value['fires'] === undefined) return false;
    return true;
}

export function RecentFiresResponseFromJSON(json: any): RecentFiresResponse {
    return RecentFiresResponseFromJSONTyped(json, false);
}

export function RecentFiresResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecentFiresResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fires': ((json['fires'] as Array<any>).map(RecentFireEntryFromJSON)),
    };
}

export function RecentFiresResponseToJSON(json: any): RecentFiresResponse {
    return RecentFiresResponseToJSONTyped(json, false);
}

export function RecentFiresResponseToJSONTyped(value?: RecentFiresResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fires': ((value['fires'] as Array<any>).map(RecentFireEntryToJSON)),
    };
}

