/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDeviceRequest
 */
export interface RegisterDeviceRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterDeviceRequest
     */
    bundle_id?: string | null;
    /**
     * Hex APNs device token
     * @type {string}
     * @memberof RegisterDeviceRequest
     */
    token: string;
}

/**
 * Check if a given object implements the RegisterDeviceRequest interface.
 */
export function instanceOfRegisterDeviceRequest(value: object): value is RegisterDeviceRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function RegisterDeviceRequestFromJSON(json: any): RegisterDeviceRequest {
    return RegisterDeviceRequestFromJSONTyped(json, false);
}

export function RegisterDeviceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDeviceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bundle_id': json['bundle_id'] == null ? undefined : json['bundle_id'],
        'token': json['token'],
    };
}

export function RegisterDeviceRequestToJSON(json: any): RegisterDeviceRequest {
    return RegisterDeviceRequestToJSONTyped(json, false);
}

export function RegisterDeviceRequestToJSONTyped(value?: RegisterDeviceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bundle_id': value['bundle_id'],
        'token': value['token'],
    };
}

