/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterDeviceResponse
 */
export interface RegisterDeviceResponse {
    /**
     * 
     * @type {number}
     * @memberof RegisterDeviceResponse
     */
    device_id: number;
    /**
     * 
     * @type {boolean}
     * @memberof RegisterDeviceResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the RegisterDeviceResponse interface.
 */
export function instanceOfRegisterDeviceResponse(value: object): value is RegisterDeviceResponse {
    if (!('device_id' in value) || value['device_id'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function RegisterDeviceResponseFromJSON(json: any): RegisterDeviceResponse {
    return RegisterDeviceResponseFromJSONTyped(json, false);
}

export function RegisterDeviceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDeviceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'device_id': json['device_id'],
        'success': json['success'],
    };
}

export function RegisterDeviceResponseToJSON(json: any): RegisterDeviceResponse {
    return RegisterDeviceResponseToJSONTyped(json, false);
}

export function RegisterDeviceResponseToJSONTyped(value?: RegisterDeviceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['device_id'],
        'success': value['success'],
    };
}

