/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RuleResponse
 */
export interface RuleResponse {
    /**
     * 
     * @type {number}
     * @memberof RuleResponse
     */
    display_order?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof RuleResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof RuleResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof RuleResponse
     */
    last_fired_at?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RuleResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RuleResponse
     */
    preset_id: string | null;
    /**
     * 
     * @type {object}
     * @memberof RuleResponse
     */
    spec: object;
    /**
     * 
     * @type {Date}
     * @memberof RuleResponse
     */
    updated_at?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof RuleResponse
     */
    version: number;
}

/**
 * Check if a given object implements the RuleResponse interface.
 */
export function instanceOfRuleResponse(value: object): value is RuleResponse {
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('preset_id' in value) || value['preset_id'] === undefined) return false;
    if (!('spec' in value) || value['spec'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function RuleResponseFromJSON(json: any): RuleResponse {
    return RuleResponseFromJSONTyped(json, false);
}

export function RuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RuleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'display_order': json['display_order'] == null ? undefined : json['display_order'],
        'enabled': json['enabled'],
        'id': json['id'],
        'last_fired_at': json['last_fired_at'] == null ? undefined : (new Date(json['last_fired_at'])),
        'name': json['name'],
        'preset_id': json['preset_id'],
        'spec': json['spec'],
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'version': json['version'],
    };
}

export function RuleResponseToJSON(json: any): RuleResponse {
    return RuleResponseToJSONTyped(json, false);
}

export function RuleResponseToJSONTyped(value?: RuleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_order': value['display_order'],
        'enabled': value['enabled'],
        'id': value['id'],
        'last_fired_at': value['last_fired_at'] == null ? value['last_fired_at'] : value['last_fired_at'].toISOString(),
        'name': value['name'],
        'preset_id': value['preset_id'],
        'spec': value['spec'],
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
        'version': value['version'],
    };
}

