/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledDepartureRequest
 */
export interface ScheduledDepartureRequest {
    /**
     * When the user intends to drive off (UTC).
     * @type {Date}
     * @memberof ScheduledDepartureRequest
     */
    departure_at_utc: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledDepartureRequest
     */
    enabled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ScheduledDepartureRequest
     */
    label?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduledDepartureRequest
     */
    lead_minutes?: number;
    /**
     * 
     * @type {number}
     * @memberof ScheduledDepartureRequest
     */
    target_charge_soc?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledDepartureRequest
     */
    vehicle_id?: string | null;
}

/**
 * Check if a given object implements the ScheduledDepartureRequest interface.
 */
export function instanceOfScheduledDepartureRequest(value: object): value is ScheduledDepartureRequest {
    if (!('departure_at_utc' in value) || value['departure_at_utc'] === undefined) return false;
    return true;
}

export function ScheduledDepartureRequestFromJSON(json: any): ScheduledDepartureRequest {
    return ScheduledDepartureRequestFromJSONTyped(json, false);
}

export function ScheduledDepartureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledDepartureRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'departure_at_utc': (new Date(json['departure_at_utc'])),
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'label': json['label'] == null ? undefined : json['label'],
        'lead_minutes': json['lead_minutes'] == null ? undefined : json['lead_minutes'],
        'target_charge_soc': json['target_charge_soc'] == null ? undefined : json['target_charge_soc'],
        'vehicle_id': json['vehicle_id'] == null ? undefined : json['vehicle_id'],
    };
}

export function ScheduledDepartureRequestToJSON(json: any): ScheduledDepartureRequest {
    return ScheduledDepartureRequestToJSONTyped(json, false);
}

export function ScheduledDepartureRequestToJSONTyped(value?: ScheduledDepartureRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'departure_at_utc': value['departure_at_utc'].toISOString(),
        'enabled': value['enabled'],
        'label': value['label'],
        'lead_minutes': value['lead_minutes'],
        'target_charge_soc': value['target_charge_soc'],
        'vehicle_id': value['vehicle_id'],
    };
}

