/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScheduledDepartureResponse
 */
export interface ScheduledDepartureResponse {
    /**
     * 
     * @type {number}
     * @memberof ScheduledDepartureResponse
     */
    id: number;
    /**
     * 
     * @type {Date}
     * @memberof ScheduledDepartureResponse
     */
    departure_at_utc: Date;
    /**
     * 
     * @type {number}
     * @memberof ScheduledDepartureResponse
     */
    lead_minutes: number;
    /**
     * 
     * @type {string}
     * @memberof ScheduledDepartureResponse
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ScheduledDepartureResponse
     */
    vehicle_id?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ScheduledDepartureResponse
     */
    target_charge_soc?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof ScheduledDepartureResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ScheduledDepartureResponse
     */
    fire_at_utc: Date;
    /**
     * 
     * @type {Date}
     * @memberof ScheduledDepartureResponse
     */
    created_at?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ScheduledDepartureResponse
     */
    updated_at?: Date | null;
}

/**
 * Check if a given object implements the ScheduledDepartureResponse interface.
 */
export function instanceOfScheduledDepartureResponse(value: object): value is ScheduledDepartureResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('departure_at_utc' in value) || value['departure_at_utc'] === undefined) return false;
    if (!('lead_minutes' in value) || value['lead_minutes'] === undefined) return false;
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    if (!('fire_at_utc' in value) || value['fire_at_utc'] === undefined) return false;
    return true;
}

export function ScheduledDepartureResponseFromJSON(json: any): ScheduledDepartureResponse {
    return ScheduledDepartureResponseFromJSONTyped(json, false);
}

export function ScheduledDepartureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduledDepartureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'departure_at_utc': (new Date(json['departure_at_utc'])),
        'lead_minutes': json['lead_minutes'],
        'label': json['label'] == null ? undefined : json['label'],
        'vehicle_id': json['vehicle_id'] == null ? undefined : json['vehicle_id'],
        'target_charge_soc': json['target_charge_soc'] == null ? undefined : json['target_charge_soc'],
        'enabled': json['enabled'],
        'fire_at_utc': (new Date(json['fire_at_utc'])),
        'created_at': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updated_at': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function ScheduledDepartureResponseToJSON(json: any): ScheduledDepartureResponse {
    return ScheduledDepartureResponseToJSONTyped(json, false);
}

export function ScheduledDepartureResponseToJSONTyped(value?: ScheduledDepartureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'departure_at_utc': value['departure_at_utc'].toISOString(),
        'lead_minutes': value['lead_minutes'],
        'label': value['label'],
        'vehicle_id': value['vehicle_id'],
        'target_charge_soc': value['target_charge_soc'],
        'enabled': value['enabled'],
        'fire_at_utc': value['fire_at_utc'].toISOString(),
        'created_at': value['created_at'] == null ? value['created_at'] : value['created_at'].toISOString(),
        'updated_at': value['updated_at'] == null ? value['updated_at'] : value['updated_at'].toISOString(),
    };
}

