/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SnoozeResponse } from './SnoozeResponse';
import {
    SnoozeResponseFromJSON,
    SnoozeResponseFromJSONTyped,
    SnoozeResponseToJSON,
    SnoozeResponseToJSONTyped,
} from './SnoozeResponse';

/**
 * 
 * @export
 * @interface SnoozeListResponse
 */
export interface SnoozeListResponse {
    /**
     * 
     * @type {Array<SnoozeResponse>}
     * @memberof SnoozeListResponse
     */
    snoozes: Array<SnoozeResponse>;
}

/**
 * Check if a given object implements the SnoozeListResponse interface.
 */
export function instanceOfSnoozeListResponse(value: object): value is SnoozeListResponse {
    if (!('snoozes' in value) || value['snoozes'] === undefined) return false;
    return true;
}

export function SnoozeListResponseFromJSON(json: any): SnoozeListResponse {
    return SnoozeListResponseFromJSONTyped(json, false);
}

export function SnoozeListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnoozeListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'snoozes': ((json['snoozes'] as Array<any>).map(SnoozeResponseFromJSON)),
    };
}

export function SnoozeListResponseToJSON(json: any): SnoozeListResponse {
    return SnoozeListResponseToJSONTyped(json, false);
}

export function SnoozeListResponseToJSONTyped(value?: SnoozeListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snoozes': ((value['snoozes'] as Array<any>).map(SnoozeResponseToJSON)),
    };
}

