/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestChargeLimitRequest
 */
export interface SuggestChargeLimitRequest {
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitRequest
     */
    current_limit?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitRequest
     */
    daily_limit_soc?: number;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitRequest
     */
    trip_limit_soc?: number;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitRequest
     */
    trip_window_hours?: number;
}

/**
 * Check if a given object implements the SuggestChargeLimitRequest interface.
 */
export function instanceOfSuggestChargeLimitRequest(value: object): value is SuggestChargeLimitRequest {
    return true;
}

export function SuggestChargeLimitRequestFromJSON(json: any): SuggestChargeLimitRequest {
    return SuggestChargeLimitRequestFromJSONTyped(json, false);
}

export function SuggestChargeLimitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestChargeLimitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'current_limit': json['current_limit'] == null ? undefined : json['current_limit'],
        'daily_limit_soc': json['daily_limit_soc'] == null ? undefined : json['daily_limit_soc'],
        'trip_limit_soc': json['trip_limit_soc'] == null ? undefined : json['trip_limit_soc'],
        'trip_window_hours': json['trip_window_hours'] == null ? undefined : json['trip_window_hours'],
    };
}

export function SuggestChargeLimitRequestToJSON(json: any): SuggestChargeLimitRequest {
    return SuggestChargeLimitRequestToJSONTyped(json, false);
}

export function SuggestChargeLimitRequestToJSONTyped(value?: SuggestChargeLimitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_limit': value['current_limit'],
        'daily_limit_soc': value['daily_limit_soc'],
        'trip_limit_soc': value['trip_limit_soc'],
        'trip_window_hours': value['trip_window_hours'],
    };
}

