/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuggestChargeLimitResponse
 */
export interface SuggestChargeLimitResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SuggestChargeLimitResponse
     */
    already_matches: boolean;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitResponse
     */
    current_percent: number | null;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitResponse
     */
    hours_away: number | null;
    /**
     * 
     * @type {string}
     * @memberof SuggestChargeLimitResponse
     */
    reason: string;
    /**
     * 
     * @type {number}
     * @memberof SuggestChargeLimitResponse
     */
    recommended_percent: number;
}

/**
 * Check if a given object implements the SuggestChargeLimitResponse interface.
 */
export function instanceOfSuggestChargeLimitResponse(value: object): value is SuggestChargeLimitResponse {
    if (!('already_matches' in value) || value['already_matches'] === undefined) return false;
    if (!('current_percent' in value) || value['current_percent'] === undefined) return false;
    if (!('hours_away' in value) || value['hours_away'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    if (!('recommended_percent' in value) || value['recommended_percent'] === undefined) return false;
    return true;
}

export function SuggestChargeLimitResponseFromJSON(json: any): SuggestChargeLimitResponse {
    return SuggestChargeLimitResponseFromJSONTyped(json, false);
}

export function SuggestChargeLimitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuggestChargeLimitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'already_matches': json['already_matches'],
        'current_percent': json['current_percent'],
        'hours_away': json['hours_away'],
        'reason': json['reason'],
        'recommended_percent': json['recommended_percent'],
    };
}

export function SuggestChargeLimitResponseToJSON(json: any): SuggestChargeLimitResponse {
    return SuggestChargeLimitResponseToJSONTyped(json, false);
}

export function SuggestChargeLimitResponseToJSONTyped(value?: SuggestChargeLimitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'already_matches': value['already_matches'],
        'current_percent': value['current_percent'],
        'hours_away': value['hours_away'],
        'reason': value['reason'],
        'recommended_percent': value['recommended_percent'],
    };
}

