/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One ``tel:<entity>:since`` + value pair from automation_state.
 * @export
 * @interface TelemetryStateEntry
 */
export interface TelemetryStateEntry {
    /**
     * 
     * @type {string}
     * @memberof TelemetryStateEntry
     */
    entity: string;
    /**
     * 
     * @type {}
     * @memberof TelemetryStateEntry
     */
    value:  | null;
    /**
     * 
     * @type {Date}
     * @memberof TelemetryStateEntry
     */
    since: Date;
}

/**
 * Check if a given object implements the TelemetryStateEntry interface.
 */
export function instanceOfTelemetryStateEntry(value: object): value is TelemetryStateEntry {
    if (!('entity' in value) || value['entity'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('since' in value) || value['since'] === undefined) return false;
    return true;
}

export function TelemetryStateEntryFromJSON(json: any): TelemetryStateEntry {
    return TelemetryStateEntryFromJSONTyped(json, false);
}

export function TelemetryStateEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TelemetryStateEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'entity': json['entity'],
        'value': FromJSON(json['value']),
        'since': (new Date(json['since'])),
    };
}

export function TelemetryStateEntryToJSON(json: any): TelemetryStateEntry {
    return TelemetryStateEntryToJSONTyped(json, false);
}

export function TelemetryStateEntryToJSONTyped(value?: TelemetryStateEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entity': value['entity'],
        'value': ToJSON(value['value']),
        'since': value['since'].toISOString(),
    };
}

