/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Tesla OAuth callback request.
 * @export
 * @interface TeslaCallbackRequest
 */
export interface TeslaCallbackRequest {
    /**
     * 
     * @type {string}
     * @memberof TeslaCallbackRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof TeslaCallbackRequest
     */
    state: string;
}

/**
 * Check if a given object implements the TeslaCallbackRequest interface.
 */
export function instanceOfTeslaCallbackRequest(value: object): value is TeslaCallbackRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function TeslaCallbackRequestFromJSON(json: any): TeslaCallbackRequest {
    return TeslaCallbackRequestFromJSONTyped(json, false);
}

export function TeslaCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeslaCallbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'state': json['state'],
    };
}

export function TeslaCallbackRequestToJSON(json: any): TeslaCallbackRequest {
    return TeslaCallbackRequestToJSONTyped(json, false);
}

export function TeslaCallbackRequestToJSONTyped(value?: TeslaCallbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'state': value['state'],
    };
}

