/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestPushRequest
 */
export interface TestPushRequest {
    /**
     * 
     * @type {string}
     * @memberof TestPushRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TestPushRequest
     */
    body?: string;
}

/**
 * Check if a given object implements the TestPushRequest interface.
 */
export function instanceOfTestPushRequest(value: object): value is TestPushRequest {
    return true;
}

export function TestPushRequestFromJSON(json: any): TestPushRequest {
    return TestPushRequestFromJSONTyped(json, false);
}

export function TestPushRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestPushRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function TestPushRequestToJSON(json: any): TestPushRequest {
    return TestPushRequestToJSONTyped(json, false);
}

export function TestPushRequestToJSONTyped(value?: TestPushRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'body': value['body'],
    };
}

