/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSettingsRequest
 */
export interface UserSettingsRequest {
    /**
     * Full settings document. PUT replaces the keys present in this dict but leaves untouched keys alone — pass `replace_all=true` to wipe and re-seed.
     * @type {object}
     * @memberof UserSettingsRequest
     */
    settings: object;
    /**
     * 
     * @type {boolean}
     * @memberof UserSettingsRequest
     */
    replace_all?: boolean;
}

/**
 * Check if a given object implements the UserSettingsRequest interface.
 */
export function instanceOfUserSettingsRequest(value: object): value is UserSettingsRequest {
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function UserSettingsRequestFromJSON(json: any): UserSettingsRequest {
    return UserSettingsRequestFromJSONTyped(json, false);
}

export function UserSettingsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSettingsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'settings': json['settings'],
        'replace_all': json['replace_all'] == null ? undefined : json['replace_all'],
    };
}

export function UserSettingsRequestToJSON(json: any): UserSettingsRequest {
    return UserSettingsRequestToJSONTyped(json, false);
}

export function UserSettingsRequestToJSONTyped(value?: UserSettingsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'settings': value['settings'],
        'replace_all': value['replace_all'],
    };
}

