/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VehicleResponse } from './VehicleResponse';
import {
    VehicleResponseFromJSON,
    VehicleResponseFromJSONTyped,
    VehicleResponseToJSON,
    VehicleResponseToJSONTyped,
} from './VehicleResponse';

/**
 * Vehicle list response.
 * @export
 * @interface VehicleListResponse
 */
export interface VehicleListResponse {
    /**
     * 
     * @type {number}
     * @memberof VehicleListResponse
     */
    count: number;
    /**
     * 
     * @type {Array<VehicleResponse>}
     * @memberof VehicleListResponse
     */
    vehicles: Array<VehicleResponse>;
}

/**
 * Check if a given object implements the VehicleListResponse interface.
 */
export function instanceOfVehicleListResponse(value: object): value is VehicleListResponse {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('vehicles' in value) || value['vehicles'] === undefined) return false;
    return true;
}

export function VehicleListResponseFromJSON(json: any): VehicleListResponse {
    return VehicleListResponseFromJSONTyped(json, false);
}

export function VehicleListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'vehicles': ((json['vehicles'] as Array<any>).map(VehicleResponseFromJSON)),
    };
}

export function VehicleListResponseToJSON(json: any): VehicleListResponse {
    return VehicleListResponseToJSONTyped(json, false);
}

export function VehicleListResponseToJSONTyped(value?: VehicleListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'vehicles': ((value['vehicles'] as Array<any>).map(VehicleResponseToJSON)),
    };
}

