/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Vehicle response model.
 * @export
 * @interface VehicleResponse
 */
export interface VehicleResponse {
    /**
     * 
     * @type {string}
     * @memberof VehicleResponse
     */
    display_name: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof VehicleResponse
     */
    is_primary?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponse
     */
    model?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponse
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleResponse
     */
    vin?: string | null;
}

/**
 * Check if a given object implements the VehicleResponse interface.
 */
export function instanceOfVehicleResponse(value: object): value is VehicleResponse {
    if (!('display_name' in value) || value['display_name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function VehicleResponseFromJSON(json: any): VehicleResponse {
    return VehicleResponseFromJSONTyped(json, false);
}

export function VehicleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'display_name': json['display_name'],
        'id': json['id'],
        'is_primary': json['is_primary'] == null ? undefined : json['is_primary'],
        'model': json['model'] == null ? undefined : json['model'],
        'state': json['state'],
        'vin': json['vin'] == null ? undefined : json['vin'],
    };
}

export function VehicleResponseToJSON(json: any): VehicleResponse {
    return VehicleResponseToJSONTyped(json, false);
}

export function VehicleResponseToJSONTyped(value?: VehicleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['display_name'],
        'id': value['id'],
        'is_primary': value['is_primary'],
        'model': value['model'],
        'state': value['state'],
        'vin': value['vin'],
    };
}

