/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Wake response model.
 * @export
 * @interface WakeResponse
 */
export interface WakeResponse {
    /**
     * 
     * @type {string}
     * @memberof WakeResponse
     */
    vehicle_id: string;
    /**
     * 
     * @type {string}
     * @memberof WakeResponse
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof WakeResponse
     */
    message: string;
}

/**
 * Check if a given object implements the WakeResponse interface.
 */
export function instanceOfWakeResponse(value: object): value is WakeResponse {
    if (!('vehicle_id' in value) || value['vehicle_id'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function WakeResponseFromJSON(json: any): WakeResponse {
    return WakeResponseFromJSONTyped(json, false);
}

export function WakeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WakeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'vehicle_id': json['vehicle_id'],
        'state': json['state'],
        'message': json['message'],
    };
}

export function WakeResponseToJSON(json: any): WakeResponse {
    return WakeResponseToJSONTyped(json, false);
}

export function WakeResponseToJSONTyped(value?: WakeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'vehicle_id': value['vehicle_id'],
        'state': value['state'],
        'message': value['message'],
    };
}

