/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WeChat login response.
 * @export
 * @interface WeChatLoginResponse
 */
export interface WeChatLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof WeChatLoginResponse
     */
    access_token: string;
    /**
     * 
     * @type {string}
     * @memberof WeChatLoginResponse
     */
    token_type?: string;
    /**
     * 
     * @type {number}
     * @memberof WeChatLoginResponse
     */
    expires_in: number;
    /**
     * 
     * @type {number}
     * @memberof WeChatLoginResponse
     */
    user_id: number;
    /**
     * 
     * @type {string}
     * @memberof WeChatLoginResponse
     */
    openid: string;
    /**
     * 
     * @type {boolean}
     * @memberof WeChatLoginResponse
     */
    has_tesla_linked?: boolean;
}

/**
 * Check if a given object implements the WeChatLoginResponse interface.
 */
export function instanceOfWeChatLoginResponse(value: object): value is WeChatLoginResponse {
    if (!('access_token' in value) || value['access_token'] === undefined) return false;
    if (!('expires_in' in value) || value['expires_in'] === undefined) return false;
    if (!('user_id' in value) || value['user_id'] === undefined) return false;
    if (!('openid' in value) || value['openid'] === undefined) return false;
    return true;
}

export function WeChatLoginResponseFromJSON(json: any): WeChatLoginResponse {
    return WeChatLoginResponseFromJSONTyped(json, false);
}

export function WeChatLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeChatLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access_token': json['access_token'],
        'token_type': json['token_type'] == null ? undefined : json['token_type'],
        'expires_in': json['expires_in'],
        'user_id': json['user_id'],
        'openid': json['openid'],
        'has_tesla_linked': json['has_tesla_linked'] == null ? undefined : json['has_tesla_linked'],
    };
}

export function WeChatLoginResponseToJSON(json: any): WeChatLoginResponse {
    return WeChatLoginResponseToJSONTyped(json, false);
}

export function WeChatLoginResponseToJSONTyped(value?: WeChatLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['access_token'],
        'token_type': value['token_type'],
        'expires_in': value['expires_in'],
        'user_id': value['user_id'],
        'openid': value['openid'],
        'has_tesla_linked': value['has_tesla_linked'],
    };
}

