/* tslint:disable */
/* eslint-disable */
/**
 * Tautomation
 * Tesla intelligent charging route planner for highway service areas
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * WeChat login request.
 * @export
 * @interface WeChatLoginRequest
 */
export interface WeChatLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof WeChatLoginRequest
     */
    code: string;
}

/**
 * Check if a given object implements the WeChatLoginRequest interface.
 */
export function instanceOfWeChatLoginRequest(value: object): value is WeChatLoginRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function WeChatLoginRequestFromJSON(json: any): WeChatLoginRequest {
    return WeChatLoginRequestFromJSONTyped(json, false);
}

export function WeChatLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WeChatLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function WeChatLoginRequestToJSON(json: any): WeChatLoginRequest {
    return WeChatLoginRequestToJSONTyped(json, false);
}

export function WeChatLoginRequestToJSONTyped(value?: WeChatLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
    };
}

