/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.POIInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Phase 8.2: greedy charging-stop selection over client-provided POIs. The iOS client gathers POIs via AMap SDK along-route search (proper road corridor) and posts them here.
 *
 * @param polyline [[lat, lng], …]
 * @param totalDistanceKm 
 * @param candidatePois 
 * @param initialSoc 
 * @param carType 
 * @param minArrivalSoc 
 * @param vehicleRangeKm 
 */


data class ChargingPlanRequest (

    /* [[lat, lng], …] */
    @Json(name = "polyline")
    val polyline: kotlin.collections.List<kotlin.collections.List<java.math.BigDecimal>>,

    @Json(name = "total_distance_km")
    val totalDistanceKm: java.math.BigDecimal,

    @Json(name = "candidate_pois")
    val candidatePois: kotlin.collections.List<POIInput>,

    @Json(name = "initial_soc")
    val initialSoc: kotlin.Int,

    @Json(name = "car_type")
    val carType: kotlin.String? = "model_y_long_range",

    @Json(name = "min_arrival_soc")
    val minArrivalSoc: kotlin.Int? = 20,

    @Json(name = "vehicle_range_km")
    val vehicleRangeKm: java.math.BigDecimal? = null

) {


}

