/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Charging stop in route.
 *
 * @param stationId 
 * @param name 
 * @param latitude 
 * @param longitude 
 * @param distanceFromStartKm 
 * @param arrivalSoc 
 * @param departureSoc 
 * @param chargingDurationMinutes 
 * @param address 
 * @param `operator` 
 */


data class ChargingStopResponse (

    @Json(name = "station_id")
    val stationId: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,

    @Json(name = "distance_from_start_km")
    val distanceFromStartKm: java.math.BigDecimal,

    @Json(name = "arrival_soc")
    val arrivalSoc: kotlin.Int,

    @Json(name = "departure_soc")
    val departureSoc: kotlin.Int,

    @Json(name = "charging_duration_minutes")
    val chargingDurationMinutes: kotlin.Int,

    @Json(name = "address")
    val address: kotlin.String? = null,

    @Json(name = "operator")
    val `operator`: kotlin.String? = null

) {


}

