/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.ChargingStopResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Output: just the charging-related fields. The iOS client merges this with the previously-fetched route data to produce its RoutePlanResponse-shape view model.
 *
 * @param chargingStops 
 * @param numChargingStops 
 * @param chargingDurationMinutes 
 * @param arrivalSoc 
 * @param warnings 
 */


data class ChargingPlanResponse (

    @Json(name = "charging_stops")
    val chargingStops: kotlin.collections.List<ChargingStopResponse>,

    @Json(name = "num_charging_stops")
    val numChargingStops: kotlin.Int,

    @Json(name = "charging_duration_minutes")
    val chargingDurationMinutes: kotlin.Int,

    @Json(name = "arrival_soc")
    val arrivalSoc: kotlin.Int,

    @Json(name = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>? = null

) {


}

