/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param startedAt 
 * @param clientSessionId 
 * @param endedAt 
 * @param startSoc 
 * @param endSoc 
 * @param startRangeKm 
 * @param endRangeKm 
 * @param energyAddedKwh 
 * @param locationName 
 * @param lat 
 * @param lng 
 * @param endedAsComplete 
 */


data class ChargingSessionRequest (

    @Json(name = "started_at")
    val startedAt: java.time.OffsetDateTime,

    @Json(name = "client_session_id")
    val clientSessionId: kotlin.String? = null,

    @Json(name = "ended_at")
    val endedAt: java.time.OffsetDateTime? = null,

    @Json(name = "start_soc")
    val startSoc: kotlin.Int? = null,

    @Json(name = "end_soc")
    val endSoc: kotlin.Int? = null,

    @Json(name = "start_range_km")
    val startRangeKm: java.math.BigDecimal? = null,

    @Json(name = "end_range_km")
    val endRangeKm: java.math.BigDecimal? = null,

    @Json(name = "energy_added_kwh")
    val energyAddedKwh: java.math.BigDecimal? = null,

    @Json(name = "location_name")
    val locationName: kotlin.String? = null,

    @Json(name = "lat")
    val lat: java.math.BigDecimal? = null,

    @Json(name = "lng")
    val lng: java.math.BigDecimal? = null,

    @Json(name = "ended_as_complete")
    val endedAsComplete: kotlin.Boolean? = null

) {


}

