/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Set climate keeper mode (0=off, 1=keep, 2=dog, 3=camp).
 *
 * @param mode 
 */


data class ClimateKeeperModeRequest (

    @Json(name = "mode")
    val mode: kotlin.Int

) {


}

