/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Email login request.
 *
 * @param email 
 * @param password 
 */


data class EmailLoginRequest (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "password")
    val password: kotlin.String

) {


}

