/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Email auth response.
 *
 * @param accessToken 
 * @param email 
 * @param expiresIn 
 * @param userId 
 * @param hasTeslaLinked 
 * @param nickname 
 * @param tokenType 
 */


data class EmailAuthResponse (

    @Json(name = "access_token")
    val accessToken: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "expires_in")
    val expiresIn: kotlin.Int,

    @Json(name = "user_id")
    val userId: kotlin.Int,

    @Json(name = "has_tesla_linked")
    val hasTeslaLinked: kotlin.Boolean? = false,

    @Json(name = "nickname")
    val nickname: kotlin.String? = null,

    @Json(name = "token_type")
    val tokenType: kotlin.String? = "Bearer"

) {


}

