/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Geocode response.
 *
 * @param latitude 
 * @param longitude 
 * @param address 
 * @param formattedAddress 
 */


data class GeocodeResponse (

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "formatted_address")
    val formattedAddress: kotlin.String? = null

) {


}

