/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.LocationInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Request to send route to vehicle.
 *
 * @param vehicleId 
 * @param waypoints 
 */


data class NavigateRouteRequest (

    @Json(name = "vehicle_id")
    val vehicleId: kotlin.String,

    @Json(name = "waypoints")
    val waypoints: kotlin.collections.List<LocationInput>? = null

) {


}

