/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param capability 
 * @param expectedState 
 * @param dispatchedAt 
 * @param status 
 * @param confirmedAt 
 * @param timedOutAt 
 */


data class PendingCommandResponse (

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "capability")
    val capability: kotlin.String,

    @Json(name = "expected_state")
    val expectedState: kotlin.Any,

    @Json(name = "dispatched_at")
    val dispatchedAt: java.time.OffsetDateTime,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "confirmed_at")
    val confirmedAt: java.time.OffsetDateTime? = null,

    @Json(name = "timed_out_at")
    val timedOutAt: java.time.OffsetDateTime? = null

) {


}

