/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Candidate POI for the charging-plan endpoint. Shape mirrors AMapRoutePOI (iOS SDK) — only id / name / lat / lng required.
 *
 * @param id 
 * @param latitude 
 * @param longitude 
 * @param name 
 * @param address 
 */


data class POIInput (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "address")
    val address: kotlin.String? = null

) {


}

