/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param capability 
 * @param dispatchPolicy 
 * @param id 
 * @param params 
 * @param queuedAt 
 * @param status 
 * @param ttlSeconds 
 * @param droppedAt 
 * @param error 
 * @param sentAt 
 */


data class QueuedCommandResponse (

    @Json(name = "capability")
    val capability: kotlin.String,

    @Json(name = "dispatch_policy")
    val dispatchPolicy: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "params")
    val params: kotlin.Any,

    @Json(name = "queued_at")
    val queuedAt: java.time.OffsetDateTime,

    @Json(name = "status")
    val status: kotlin.String,

    @Json(name = "ttl_seconds")
    val ttlSeconds: kotlin.Int,

    @Json(name = "dropped_at")
    val droppedAt: java.time.OffsetDateTime? = null,

    @Json(name = "error")
    val error: kotlin.String? = null,

    @Json(name = "sent_at")
    val sentAt: java.time.OffsetDateTime? = null

) {


}

