/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.ChargingStopResponse

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Route planning response.
 *
 * @param origin 
 * @param destination 
 * @param totalDistanceKm 
 * @param totalDurationMinutes 
 * @param drivingDurationMinutes 
 * @param chargingDurationMinutes 
 * @param chargingStops 
 * @param numChargingStops 
 * @param initialSoc 
 * @param arrivalSoc 
 * @param routeId 
 * @param polyline 
 * @param warnings 
 */


data class RoutePlanResponse (

    @Json(name = "origin")
    val origin: kotlin.Any,

    @Json(name = "destination")
    val destination: kotlin.Any,

    @Json(name = "total_distance_km")
    val totalDistanceKm: java.math.BigDecimal,

    @Json(name = "total_duration_minutes")
    val totalDurationMinutes: kotlin.Int,

    @Json(name = "driving_duration_minutes")
    val drivingDurationMinutes: kotlin.Int,

    @Json(name = "charging_duration_minutes")
    val chargingDurationMinutes: kotlin.Int,

    @Json(name = "charging_stops")
    val chargingStops: kotlin.collections.List<ChargingStopResponse>,

    @Json(name = "num_charging_stops")
    val numChargingStops: kotlin.Int,

    @Json(name = "initial_soc")
    val initialSoc: kotlin.Int,

    @Json(name = "arrival_soc")
    val arrivalSoc: kotlin.Int,

    @Json(name = "route_id")
    val routeId: kotlin.Int? = null,

    @Json(name = "polyline")
    val polyline: kotlin.collections.List<kotlin.Any>? = null,

    @Json(name = "warnings")
    val warnings: kotlin.collections.List<kotlin.String>? = null

) {


}

