/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.LocationInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Phase 8.2: route metadata only (no charging plan).  Used by the iOS client to get the polyline first, then run AMap SDK along-route POI search locally, then post the candidate POIs back via /charging-plan to compute the greedy charging stops.
 *
 * @param destination 
 * @param origin 
 */


data class RouteOnlyRequest (

    @Json(name = "destination")
    val destination: LocationInput,

    @Json(name = "origin")
    val origin: LocationInput

) {


}

