/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param enabled 
 * @param id 
 * @param name 
 * @param presetId 
 * @param spec 
 * @param version 
 * @param displayOrder 
 * @param lastFiredAt 
 * @param updatedAt 
 */


data class RuleResponse (

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "preset_id")
    val presetId: kotlin.String?,

    @Json(name = "spec")
    val spec: kotlin.Any,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "display_order")
    val displayOrder: kotlin.Int? = null,

    @Json(name = "last_fired_at")
    val lastFiredAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

