/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param departureAtUtc When the user intends to drive off (UTC).
 * @param enabled 
 * @param label 
 * @param leadMinutes 
 * @param targetChargeSoc 
 * @param vehicleId 
 */


data class ScheduledDepartureRequest (

    /* When the user intends to drive off (UTC). */
    @Json(name = "departure_at_utc")
    val departureAtUtc: java.time.OffsetDateTime,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean? = true,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "lead_minutes")
    val leadMinutes: kotlin.Int? = 15,

    @Json(name = "target_charge_soc")
    val targetChargeSoc: kotlin.Int? = null,

    @Json(name = "vehicle_id")
    val vehicleId: kotlin.String? = null

) {


}

