/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param departureAtUtc 
 * @param enabled 
 * @param fireAtUtc 
 * @param id 
 * @param leadMinutes 
 * @param createdAt 
 * @param label 
 * @param targetChargeSoc 
 * @param updatedAt 
 * @param vehicleId 
 */


data class ScheduledDepartureResponse (

    @Json(name = "departure_at_utc")
    val departureAtUtc: java.time.OffsetDateTime,

    @Json(name = "enabled")
    val enabled: kotlin.Boolean,

    @Json(name = "fire_at_utc")
    val fireAtUtc: java.time.OffsetDateTime,

    @Json(name = "id")
    val id: kotlin.Int,

    @Json(name = "lead_minutes")
    val leadMinutes: kotlin.Int,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "label")
    val label: kotlin.String? = null,

    @Json(name = "target_charge_soc")
    val targetChargeSoc: kotlin.Int? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,

    @Json(name = "vehicle_id")
    val vehicleId: kotlin.String? = null

) {


}

