/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models

import cloud.teplanner.api.models.ChargingStation

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Station search response.
 *
 * @param count 
 * @param stations 
 */


data class StationSearchResponse (

    @Json(name = "count")
    val count: kotlin.Int,

    @Json(name = "stations")
    val stations: kotlin.collections.List<ChargingStation>

) {


}

