/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param currentLimit 
 * @param dailyLimitSoc 
 * @param tripLimitSoc 
 * @param tripWindowHours 
 */


data class SuggestChargeLimitRequest (

    @Json(name = "current_limit")
    val currentLimit: kotlin.Int? = null,

    @Json(name = "daily_limit_soc")
    val dailyLimitSoc: kotlin.Int? = 80,

    @Json(name = "trip_limit_soc")
    val tripLimitSoc: kotlin.Int? = 100,

    @Json(name = "trip_window_hours")
    val tripWindowHours: kotlin.Int? = 12

) {


}

