/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param recommendedPercent 
 * @param currentPercent 
 * @param reason 
 * @param hoursAway 
 * @param alreadyMatches 
 */


data class SuggestChargeLimitResponse (

    @Json(name = "recommended_percent")
    val recommendedPercent: kotlin.Int,

    @Json(name = "current_percent")
    val currentPercent: kotlin.Int?,

    @Json(name = "reason")
    val reason: kotlin.String,

    @Json(name = "hours_away")
    val hoursAway: kotlin.Int?,

    @Json(name = "already_matches")
    val alreadyMatches: kotlin.Boolean

) {


}

