/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Vehicle response model.
 *
 * @param id 
 * @param displayName 
 * @param state 
 * @param vin 
 * @param model 
 * @param isPrimary 
 */


data class VehicleResponse (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "display_name")
    val displayName: kotlin.String,

    @Json(name = "state")
    val state: kotlin.String,

    @Json(name = "vin")
    val vin: kotlin.String? = null,

    @Json(name = "model")
    val model: kotlin.String? = null,

    @Json(name = "is_primary")
    val isPrimary: kotlin.Boolean? = false

) {


}

