/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package cloud.teplanner.api.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Vehicle state response.
 *
 * @param vehicleId 
 * @param displayName 
 * @param state 
 * @param batteryLevel 
 * @param batteryRangeKm 
 * @param usableBatteryLevel 
 * @param chargingState 
 * @param latitude 
 * @param longitude 
 * @param heading 
 * @param speed 
 * @param odometerKm 
 * @param insideTemp 
 * @param outsideTemp 
 * @param climateKeeperMode 
 * @param isClimateOn 
 * @param sentryModeOn 
 * @param cabinOverheatProtectionOn 
 * @param chargeLimitSoc 
 */


data class VehicleStateResponse (

    @Json(name = "vehicle_id")
    val vehicleId: kotlin.String,

    @Json(name = "display_name")
    val displayName: kotlin.String,

    @Json(name = "state")
    val state: kotlin.String,

    @Json(name = "battery_level")
    val batteryLevel: kotlin.Int? = null,

    @Json(name = "battery_range_km")
    val batteryRangeKm: java.math.BigDecimal? = null,

    @Json(name = "usable_battery_level")
    val usableBatteryLevel: kotlin.Int? = null,

    @Json(name = "charging_state")
    val chargingState: kotlin.String? = null,

    @Json(name = "latitude")
    val latitude: java.math.BigDecimal? = null,

    @Json(name = "longitude")
    val longitude: java.math.BigDecimal? = null,

    @Json(name = "heading")
    val heading: kotlin.Int? = null,

    @Json(name = "speed")
    val speed: kotlin.Int? = null,

    @Json(name = "odometer_km")
    val odometerKm: java.math.BigDecimal? = null,

    @Json(name = "inside_temp")
    val insideTemp: java.math.BigDecimal? = null,

    @Json(name = "outside_temp")
    val outsideTemp: java.math.BigDecimal? = null,

    @Json(name = "climate_keeper_mode")
    val climateKeeperMode: kotlin.Int? = null,

    @Json(name = "is_climate_on")
    val isClimateOn: kotlin.Boolean? = null,

    @Json(name = "sentry_mode_on")
    val sentryModeOn: kotlin.Boolean? = null,

    @Json(name = "cabin_overheat_protection_on")
    val cabinOverheatProtectionOn: kotlin.Boolean? = null,

    @Json(name = "charge_limit_soc")
    val chargeLimitSoc: kotlin.Int? = null

) {


}

