//
// ChargingPlanRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Phase 8.2: greedy charging-stop selection over client-provided POIs. The iOS client gathers POIs via AMap SDK along-route search (proper road corridor) and posts them here. */
public struct ChargingPlanRequest: Codable, JSONEncodable, Hashable {

    public static let initialSocRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let minArrivalSocRule = NumericRule<Int>(minimum: 5, exclusiveMinimum: false, maximum: 50, exclusiveMaximum: false, multipleOf: nil)
    public var candidatePois: [POIInput]
    public var carType: String? = "model_y_long_range"
    public var initialSoc: Int
    public var minArrivalSoc: Int? = 20
    /** [[lat, lng], …] */
    public var polyline: [[Double]]
    public var totalDistanceKm: Double
    public var vehicleRangeKm: Double?

    public init(candidatePois: [POIInput], carType: String? = "model_y_long_range", initialSoc: Int, minArrivalSoc: Int? = 20, polyline: [[Double]], totalDistanceKm: Double, vehicleRangeKm: Double? = nil) {
        self.candidatePois = candidatePois
        self.carType = carType
        self.initialSoc = initialSoc
        self.minArrivalSoc = minArrivalSoc
        self.polyline = polyline
        self.totalDistanceKm = totalDistanceKm
        self.vehicleRangeKm = vehicleRangeKm
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case candidatePois = "candidate_pois"
        case carType = "car_type"
        case initialSoc = "initial_soc"
        case minArrivalSoc = "min_arrival_soc"
        case polyline
        case totalDistanceKm = "total_distance_km"
        case vehicleRangeKm = "vehicle_range_km"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(candidatePois, forKey: .candidatePois)
        try container.encodeIfPresent(carType, forKey: .carType)
        try container.encode(initialSoc, forKey: .initialSoc)
        try container.encodeIfPresent(minArrivalSoc, forKey: .minArrivalSoc)
        try container.encode(polyline, forKey: .polyline)
        try container.encode(totalDistanceKm, forKey: .totalDistanceKm)
        try container.encodeIfPresent(vehicleRangeKm, forKey: .vehicleRangeKm)
    }
}

