//
// ChargingSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChargingSessionResponse: Codable, JSONEncodable, Hashable {

    public var clientSessionId: String?
    public var durationMinutes: Int?
    public var endRangeKm: Double?
    public var endSoc: Int?
    public var endedAsComplete: Bool?
    public var endedAt: Date?
    public var energyAddedKwh: Double?
    public var id: Int
    public var lat: Double?
    public var lng: Double?
    public var locationName: String?
    public var rangeAddedKm: Double?
    public var socDelta: Int?
    public var source: String
    public var startRangeKm: Double?
    public var startSoc: Int?
    public var startedAt: Date
    public var vehicleId: String?

    public init(clientSessionId: String?, durationMinutes: Int?, endRangeKm: Double?, endSoc: Int?, endedAsComplete: Bool?, endedAt: Date?, energyAddedKwh: Double?, id: Int, lat: Double?, lng: Double?, locationName: String?, rangeAddedKm: Double?, socDelta: Int?, source: String, startRangeKm: Double?, startSoc: Int?, startedAt: Date, vehicleId: String?) {
        self.clientSessionId = clientSessionId
        self.durationMinutes = durationMinutes
        self.endRangeKm = endRangeKm
        self.endSoc = endSoc
        self.endedAsComplete = endedAsComplete
        self.endedAt = endedAt
        self.energyAddedKwh = energyAddedKwh
        self.id = id
        self.lat = lat
        self.lng = lng
        self.locationName = locationName
        self.rangeAddedKm = rangeAddedKm
        self.socDelta = socDelta
        self.source = source
        self.startRangeKm = startRangeKm
        self.startSoc = startSoc
        self.startedAt = startedAt
        self.vehicleId = vehicleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientSessionId = "client_session_id"
        case durationMinutes = "duration_minutes"
        case endRangeKm = "end_range_km"
        case endSoc = "end_soc"
        case endedAsComplete = "ended_as_complete"
        case endedAt = "ended_at"
        case energyAddedKwh = "energy_added_kwh"
        case id
        case lat
        case lng
        case locationName = "location_name"
        case rangeAddedKm = "range_added_km"
        case socDelta = "soc_delta"
        case source
        case startRangeKm = "start_range_km"
        case startSoc = "start_soc"
        case startedAt = "started_at"
        case vehicleId = "vehicle_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientSessionId, forKey: .clientSessionId)
        try container.encode(durationMinutes, forKey: .durationMinutes)
        try container.encode(endRangeKm, forKey: .endRangeKm)
        try container.encode(endSoc, forKey: .endSoc)
        try container.encode(endedAsComplete, forKey: .endedAsComplete)
        try container.encode(endedAt, forKey: .endedAt)
        try container.encode(energyAddedKwh, forKey: .energyAddedKwh)
        try container.encode(id, forKey: .id)
        try container.encode(lat, forKey: .lat)
        try container.encode(lng, forKey: .lng)
        try container.encode(locationName, forKey: .locationName)
        try container.encode(rangeAddedKm, forKey: .rangeAddedKm)
        try container.encode(socDelta, forKey: .socDelta)
        try container.encode(source, forKey: .source)
        try container.encode(startRangeKm, forKey: .startRangeKm)
        try container.encode(startSoc, forKey: .startSoc)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(vehicleId, forKey: .vehicleId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ChargingSessionResponse: Identifiable {}
