//
// ChargeLimitRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Set the charge limit SOC percent (50..100). */
public struct ChargeLimitRequest: Codable, JSONEncodable, Hashable {

    public var percent: Int

    public init(percent: Int) {
        self.percent = percent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percent, forKey: .percent)
    }
}

