//
// ClimateKeeperModeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Set climate keeper mode (0&#x3D;off, 1&#x3D;keep, 2&#x3D;dog, 3&#x3D;camp). */
public struct ClimateKeeperModeRequest: Codable, JSONEncodable, Hashable {

    public var mode: Int

    public init(mode: Int) {
        self.mode = mode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mode, forKey: .mode)
    }
}

