//
// EmailAuthResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Email auth response. */
public struct EmailAuthResponse: Codable, JSONEncodable, Hashable {

    public var accessToken: String
    public var tokenType: String? = "Bearer"
    public var expiresIn: Int
    public var userId: Int
    public var email: String
    public var nickname: String?
    public var hasTeslaLinked: Bool? = false

    public init(accessToken: String, tokenType: String? = "Bearer", expiresIn: Int, userId: Int, email: String, nickname: String? = nil, hasTeslaLinked: Bool? = false) {
        self.accessToken = accessToken
        self.tokenType = tokenType
        self.expiresIn = expiresIn
        self.userId = userId
        self.email = email
        self.nickname = nickname
        self.hasTeslaLinked = hasTeslaLinked
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case tokenType = "token_type"
        case expiresIn = "expires_in"
        case userId = "user_id"
        case email
        case nickname
        case hasTeslaLinked = "has_tesla_linked"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encode(userId, forKey: .userId)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(nickname, forKey: .nickname)
        try container.encodeIfPresent(hasTeslaLinked, forKey: .hasTeslaLinked)
    }
}

