//
// EmailRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Email registration request. */
public struct EmailRegisterRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var password: String
    public var nickname: String?

    public init(email: String, password: String, nickname: String? = nil) {
        self.email = email
        self.password = password
        self.nickname = nickname
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case nickname
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(nickname, forKey: .nickname)
    }
}

