//
// EmailRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Email registration request. */
public struct EmailRegisterRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var nickname: String?
    public var password: String

    public init(email: String, nickname: String? = nil, password: String) {
        self.email = email
        self.nickname = nickname
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case nickname
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(nickname, forKey: .nickname)
        try container.encode(password, forKey: .password)
    }
}

