//
// PendingCommandResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PendingCommandResponse: Codable, JSONEncodable, Hashable {

    public var capability: String
    public var confirmedAt: Date?
    public var dispatchedAt: Date
    public var expectedState: AnyCodable
    public var id: Int
    public var status: String
    public var timedOutAt: Date?

    public init(capability: String, confirmedAt: Date? = nil, dispatchedAt: Date, expectedState: AnyCodable, id: Int, status: String, timedOutAt: Date? = nil) {
        self.capability = capability
        self.confirmedAt = confirmedAt
        self.dispatchedAt = dispatchedAt
        self.expectedState = expectedState
        self.id = id
        self.status = status
        self.timedOutAt = timedOutAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case capability
        case confirmedAt = "confirmed_at"
        case dispatchedAt = "dispatched_at"
        case expectedState = "expected_state"
        case id
        case status
        case timedOutAt = "timed_out_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(capability, forKey: .capability)
        try container.encodeIfPresent(confirmedAt, forKey: .confirmedAt)
        try container.encode(dispatchedAt, forKey: .dispatchedAt)
        try container.encode(expectedState, forKey: .expectedState)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(timedOutAt, forKey: .timedOutAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PendingCommandResponse: Identifiable {}
