//
// PendingCommandListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PendingCommandListResponse: Codable, JSONEncodable, Hashable {

    public var pending: [PendingCommandResponse]

    public init(pending: [PendingCommandResponse]) {
        self.pending = pending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pending, forKey: .pending)
    }
}

