//
// QueuedCommandResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QueuedCommandResponse: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var capability: String
    public var params: AnyCodable
    public var dispatchPolicy: String
    public var queuedAt: Date
    public var sentAt: Date?
    public var droppedAt: Date?
    public var ttlSeconds: Int
    public var error: String?
    public var status: String

    public init(id: Int, capability: String, params: AnyCodable, dispatchPolicy: String, queuedAt: Date, sentAt: Date? = nil, droppedAt: Date? = nil, ttlSeconds: Int, error: String? = nil, status: String) {
        self.id = id
        self.capability = capability
        self.params = params
        self.dispatchPolicy = dispatchPolicy
        self.queuedAt = queuedAt
        self.sentAt = sentAt
        self.droppedAt = droppedAt
        self.ttlSeconds = ttlSeconds
        self.error = error
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case capability
        case params
        case dispatchPolicy = "dispatch_policy"
        case queuedAt = "queued_at"
        case sentAt = "sent_at"
        case droppedAt = "dropped_at"
        case ttlSeconds = "ttl_seconds"
        case error
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(capability, forKey: .capability)
        try container.encode(params, forKey: .params)
        try container.encode(dispatchPolicy, forKey: .dispatchPolicy)
        try container.encode(queuedAt, forKey: .queuedAt)
        try container.encodeIfPresent(sentAt, forKey: .sentAt)
        try container.encodeIfPresent(droppedAt, forKey: .droppedAt)
        try container.encode(ttlSeconds, forKey: .ttlSeconds)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encode(status, forKey: .status)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QueuedCommandResponse: Identifiable {}
