//
// RecentFireEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RecentFireEntry: Codable, JSONEncodable, Hashable {

    public var kind: String
    public var pushedAt: Date
    public var clearedAt: Date?

    public init(kind: String, pushedAt: Date, clearedAt: Date? = nil) {
        self.kind = kind
        self.pushedAt = pushedAt
        self.clearedAt = clearedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kind
        case pushedAt = "pushed_at"
        case clearedAt = "cleared_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(pushedAt, forKey: .pushedAt)
        try container.encodeIfPresent(clearedAt, forKey: .clearedAt)
    }
}

