//
// RuleUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RuleUpdateRequest: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public var name: String?
    public var enabled: Bool?
    public var spec: AnyCodable?

    public init(name: String? = nil, enabled: Bool? = nil, spec: AnyCodable? = nil) {
        self.name = name
        self.enabled = enabled
        self.spec = spec
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case enabled
        case spec
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(spec, forKey: .spec)
    }
}

