//
// RuleListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RuleListResponse: Codable, JSONEncodable, Hashable {

    public var rules: [RuleResponse]

    public init(rules: [RuleResponse]) {
        self.rules = rules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rules
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rules, forKey: .rules)
    }
}

