//
// RuleCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RuleCreateRequest: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 128, pattern: nil)
    public var name: String
    public var enabled: Bool? = true
    public var spec: AnyCodable

    public init(name: String, enabled: Bool? = true, spec: AnyCodable) {
        self.name = name
        self.enabled = enabled
        self.spec = spec
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case enabled
        case spec
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encode(spec, forKey: .spec)
    }
}

