//
// SentryModeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Toggle sentry mode. */
public struct SentryModeRequest: Codable, JSONEncodable, Hashable {

    public var on: Bool

    public init(on: Bool) {
        self.on = on
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case on
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(on, forKey: .on)
    }
}

