//
// StationSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Station search response. */
public struct StationSearchResponse: Codable, JSONEncodable, Hashable {

    public var count: Int
    public var stations: [ChargingStation]

    public init(count: Int, stations: [ChargingStation]) {
        self.count = count
        self.stations = stations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case stations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(stations, forKey: .stations)
    }
}

