//
// TelemetryStateEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One &#x60;&#x60;tel:&lt;entity&gt;:since&#x60;&#x60; + value pair from automation_state. */
public struct TelemetryStateEntry: Codable, JSONEncodable, Hashable {

    public var entity: String
    public var value: AnyCodable?
    public var since: Date

    public init(entity: String, value: AnyCodable?, since: Date) {
        self.entity = entity
        self.value = value
        self.since = since
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entity
        case value
        case since
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entity, forKey: .entity)
        try container.encode(value, forKey: .value)
        try container.encode(since, forKey: .since)
    }
}

