//
// TelemetryStateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelemetryStateResponse: Codable, JSONEncodable, Hashable {

    public var vehicleId: String?
    public var entries: [TelemetryStateEntry]

    public init(vehicleId: String?, entries: [TelemetryStateEntry]) {
        self.vehicleId = vehicleId
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case vehicleId = "vehicle_id"
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(vehicleId, forKey: .vehicleId)
        try container.encode(entries, forKey: .entries)
    }
}

