//
// TelemetryStateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TelemetryStateResponse: Codable, JSONEncodable, Hashable {

    public var entries: [TelemetryStateEntry]
    public var vehicleId: String?

    public init(entries: [TelemetryStateEntry], vehicleId: String?) {
        self.entries = entries
        self.vehicleId = vehicleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entries
        case vehicleId = "vehicle_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(entries, forKey: .entries)
        try container.encode(vehicleId, forKey: .vehicleId)
    }
}

