//
// TestPushRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TestPushRequest: Codable, JSONEncodable, Hashable {

    public var body: String? = "如果你看到这条通知，APNs 已打通。"
    public var title: String? = "TePlanner 测试推送"

    public init(body: String? = "如果你看到这条通知，APNs 已打通。", title: String? = "TePlanner 测试推送") {
        self.body = body
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case body
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(body, forKey: .body)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

