//
// UserSettingsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserSettingsRequest: Codable, JSONEncodable, Hashable {

    public var replaceAll: Bool? = false
    /** Full settings document. PUT replaces the keys present in this dict but leaves untouched keys alone — pass `replace_all=true` to wipe and re-seed. */
    public var settings: AnyCodable

    public init(replaceAll: Bool? = false, settings: AnyCodable) {
        self.replaceAll = replaceAll
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case replaceAll = "replace_all"
        case settings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(replaceAll, forKey: .replaceAll)
        try container.encode(settings, forKey: .settings)
    }
}

