//
// UserSettingsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserSettingsResponse: Codable, JSONEncodable, Hashable {

    public var settings: AnyCodable
    public var updatedAt: Date?

    public init(settings: AnyCodable, updatedAt: Date? = nil) {
        self.settings = settings
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case settings
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(settings, forKey: .settings)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

