//
// VehicleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Vehicle response model. */
public struct VehicleResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var vin: String?
    public var displayName: String
    public var model: String?
    public var state: String
    public var isPrimary: Bool? = false

    public init(id: String, vin: String? = nil, displayName: String, model: String? = nil, state: String, isPrimary: Bool? = false) {
        self.id = id
        self.vin = vin
        self.displayName = displayName
        self.model = model
        self.state = state
        self.isPrimary = isPrimary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case vin
        case displayName = "display_name"
        case model
        case state
        case isPrimary = "is_primary"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(vin, forKey: .vin)
        try container.encode(displayName, forKey: .displayName)
        try container.encodeIfPresent(model, forKey: .model)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(isPrimary, forKey: .isPrimary)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VehicleResponse: Identifiable {}
