//
// WakeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Wake response model. */
public struct WakeResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var state: String
    public var vehicleId: String

    public init(message: String, state: String, vehicleId: String) {
        self.message = message
        self.state = state
        self.vehicleId = vehicleId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case state
        case vehicleId = "vehicle_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(state, forKey: .state)
        try container.encode(vehicleId, forKey: .vehicleId)
    }
}

