//
// WeChatLoginResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** WeChat login response. */
public struct WeChatLoginResponse: Codable, JSONEncodable, Hashable {

    public var accessToken: String
    public var expiresIn: Int
    public var hasTeslaLinked: Bool? = false
    public var openid: String
    public var tokenType: String? = "Bearer"
    public var userId: Int

    public init(accessToken: String, expiresIn: Int, hasTeslaLinked: Bool? = false, openid: String, tokenType: String? = "Bearer", userId: Int) {
        self.accessToken = accessToken
        self.expiresIn = expiresIn
        self.hasTeslaLinked = hasTeslaLinked
        self.openid = openid
        self.tokenType = tokenType
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case accessToken = "access_token"
        case expiresIn = "expires_in"
        case hasTeslaLinked = "has_tesla_linked"
        case openid
        case tokenType = "token_type"
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(accessToken, forKey: .accessToken)
        try container.encode(expiresIn, forKey: .expiresIn)
        try container.encodeIfPresent(hasTeslaLinked, forKey: .hasTeslaLinked)
        try container.encode(openid, forKey: .openid)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
        try container.encode(userId, forKey: .userId)
    }
}

