#!/usr/bin/env python3
"""Regenerate Tokens.swift + Tokens.kt from packages/design-tokens/tokens.json.

Lightweight Style-Dictionary alternative — pure stdlib, no npm.
Preserves cross-platform consistency: edit the JSON, run this, both
platform outputs update together. Workflow:

    edit packages/design-tokens/tokens.json
    python3 scripts/generate-tokens.py
    git diff   # review both Tokens.swift + Tokens.kt churn

CI gate (TODO): scripts/verify-tokens-frozen.sh regenerates and
fails if outputs differ from committed.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "packages" / "design-tokens" / "tokens.json"
OUT_SWIFT = ROOT / "apps" / "ios" / "Sources" / "TePlannerKit" / "Theme" / "Tokens.swift"
OUT_KOTLIN = ROOT / "apps" / "android" / "core" / "ui" / "src" / "main" / "java" / "cloud" / "teplanner" / "android" / "core" / "ui" / "Tokens.kt"


def _walk(node: Any, prefix: list[str] = []) -> list[tuple[list[str], dict]]:
    """Yield (path, leaf_dict) for every token (leaf with `value`).

    Typography leaves use a structured dict value ({size, weight?, design?}),
    so dict values are treated as a leaf when `type` is `typography`.
    """
    out = []
    if isinstance(node, dict):
        is_leaf = "value" in node and (
            not isinstance(node["value"], dict)
            or node.get("type") == "typography"
        )
        if is_leaf:
            out.append((prefix, node))
        else:
            for k, v in node.items():
                if k.startswith("$"):
                    continue
                out.extend(_walk(v, prefix + [k]))
    return out


def _camel(parts: list[str]) -> str:
    """`["color","alert","firing","bg"]` → `colorAlertFiringBg`.
    Multi-word segments split on `_` get their pieces capitalized too:
    `["color","trigger_accent","cron"]` → `colorTriggerAccentCron`.
    """
    def cap_segments(s: str, *, lead: bool) -> str:
        bits = s.split("_")
        return (bits[0] if lead else bits[0].capitalize()) + "".join(b.capitalize() for b in bits[1:])
    head, *tail = parts
    return cap_segments(head, lead=True) + "".join(cap_segments(p, lead=False) for p in tail)


def _hex_to_rgba(hexstr: str) -> tuple[float, float, float, float]:
    h = hexstr.lstrip("#")
    if len(h) == 6:
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        a = 255
    elif len(h) == 8:
        r, g, b, a = (int(h[i:i+2], 16) for i in (0, 2, 4, 6))
    else:
        raise ValueError(f"bad hex: {hexstr}")
    return r / 255.0, g / 255.0, b / 255.0, a / 255.0


def _swift_font_expr(spec: dict) -> str:
    size = spec["size"]
    weight = spec.get("weight")
    design = spec.get("design")
    args = [f"size: {size}"]
    if weight:
        args.append(f"weight: .{weight}")
    if design == "monospaced":
        args.append("design: .monospaced")
    expr = f".system({', '.join(args)})"
    if design == "monodigit":
        expr += ".monospacedDigit()"
    return expr


def emit_swift(tokens: list[tuple[list[str], dict]]) -> str:
    lines = [
        "// Generated by scripts/generate-tokens.py — do not edit by hand.",
        "// Source: packages/design-tokens/tokens.json",
        "",
        "import SwiftUI",
        "",
        "public enum Tokens {",
    ]
    ios_only_open = False
    for path, leaf in tokens:
        name = _camel(path)
        kind = leaf.get("type", "")
        needs_ios_gate = kind == "ios_system_color"
        if needs_ios_gate and not ios_only_open:
            lines.append("#if canImport(UIKit)")
            ios_only_open = True
        elif not needs_ios_gate and ios_only_open:
            lines.append("#endif")
            ios_only_open = False
        if kind == "color":
            r, g, b, a = _hex_to_rgba(leaf["value"])
            lines.append(
                f"    public static let {name} = Color("
                f"red: {r:.4f}, green: {g:.4f}, blue: {b:.4f}, opacity: {a:.4f})"
            )
        elif kind == "dimension":
            lines.append(f"    public static let {name}: CGFloat = {leaf['value']}")
        elif kind == "typography":
            lines.append(f"    public static let {name}: Font = {_swift_font_expr(leaf['value'])}")
        elif kind == "ios_system_color":
            lines.append(f"    public static let {name}: Color = Color(.{leaf['value']})")
        else:
            lines.append(f"    // skipped {name} (unknown type {kind!r})")
    if ios_only_open:
        lines.append("#endif")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


_WEIGHT_KT = {
    "regular": "FontWeight.Normal",
    "medium": "FontWeight.Medium",
    "semibold": "FontWeight.SemiBold",
    "bold": "FontWeight.Bold",
}


def _kotlin_textstyle_expr(spec: dict) -> str:
    parts = [f"fontSize = {spec['size']}.sp"]
    if w := spec.get("weight"):
        parts.append(f"fontWeight = {_WEIGHT_KT.get(w, 'FontWeight.Normal')}")
    design = spec.get("design")
    if design == "monospaced":
        parts.append("fontFamily = FontFamily.Monospace")
    elif design == "monodigit":
        parts.append('fontFeatureSettings = "\\"tnum\\""')
    return "TextStyle(" + ", ".join(parts) + ")"


def emit_kotlin(tokens: list[tuple[list[str], dict]]) -> str:
    lines = [
        "// Generated by scripts/generate-tokens.py — do not edit by hand.",
        "// Source: packages/design-tokens/tokens.json",
        "",
        "package cloud.teplanner.android.core.ui",
        "",
        "import androidx.compose.ui.graphics.Color",
        "import androidx.compose.ui.text.TextStyle",
        "import androidx.compose.ui.text.font.FontFamily",
        "import androidx.compose.ui.text.font.FontWeight",
        "import androidx.compose.ui.unit.dp",
        "import androidx.compose.ui.unit.sp",
        "",
        "object Tokens {",
    ]
    for path, leaf in tokens:
        name = _camel(path)
        kind = leaf.get("type", "")
        if kind == "color":
            h = leaf["value"].lstrip("#")
            if len(h) == 6:
                argb = "0xFF" + h.upper()
            else:
                # 8-char #RRGGBBAA → ARGB
                rgb, a = h[:6], h[6:8]
                argb = "0x" + a.upper() + rgb.upper()
            lines.append(f"    val {name} = Color({argb})")
        elif kind == "dimension":
            lines.append(f"    val {name} = {leaf['value']}.dp")
        elif kind == "typography":
            lines.append(f"    val {name} = {_kotlin_textstyle_expr(leaf['value'])}")
        elif kind == "ios_system_color":
            lines.append(
                f"    // {name}: iOS-only (Color(.{leaf['value']})). "
                "Phase F: map to MaterialTheme.colorScheme.* equivalent."
            )
        else:
            lines.append(f"    // skipped {name} (unknown type {kind!r})")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    spec = json.loads(SRC.read_text())
    tokens = _walk(spec)
    OUT_SWIFT.parent.mkdir(parents=True, exist_ok=True)
    OUT_KOTLIN.parent.mkdir(parents=True, exist_ok=True)
    OUT_SWIFT.write_text(emit_swift(tokens))
    OUT_KOTLIN.write_text(emit_kotlin(tokens))
    print(f"wrote {len(tokens)} tokens →")
    print(f"  {OUT_SWIFT}")
    print(f"  {OUT_KOTLIN}")


if __name__ == "__main__":
    main()
